### ISSUE TITLE
Localization not refreshing until UserControl is changed

### ISSUE THREAD

**Issue by lablabla** [SeriousM/WPFLocalizationExtension#104]
I have a UserControl of a settings screen. It's injected to the window using ContentControl and DataTemplate.

The UserControl has a ComboBox as in the examples with 

```
ItemsSource="{Binding Source={x:Static lex:LocalizeDictionary.Instance}, 
Path=MergedAvailableCultures}" SelectedItem="{Binding Source={x:Static lex:LocalizeDictionary.Instance}, Path=Culture, UpdateSourceTrigger=PropertyChanged}"
DisplayMemberPath="NativeName"
```

I can see all the languages in the combo box but when I change the selected item nothing happens.
If I navigate back, the previous screen will have the strings in the correct language.

Is there a way to update the UI immediately when selecting?

Thanks

**Comment by SeriousM** [comment]
Closed due stall conversation
