### ISSUE TITLE
Set LocalizeDictionary.Instance.Culture freezes the application

### ISSUE THREAD

**Issue by keke8273** [SeriousM/WPFLocalizationExtension#105]
My main UI thread spawns a new STA thread to display a splash screen on startup. Some of the texts displayed in the splash screen need to be localized. 

When I try to set the LocalizeDictionary.Instance.Culture it hangs the thread indefinitely. 

If I dont set the culture, the TextBlocks pick up the Netural text from resx file perfectly. 

version = 2.3.2

```
 private void SplashTask()
        {
            Dispatcher.CurrentDispatcher.BeginInvoke(
                              (Action)(() =>
                              {
                                  LocalizeDictionary.Instance.SetCurrentThreadCulture = true;
                                  //this is where the thread hangs
                                  LocalizeDictionary.Instance.Culture = new CultureInfo("zh-CN");

                                  _container.RegisterType<SplashScreenViewModel, SplashScreenViewModel>();
                                  _container.RegisterType<SplashScreen, SplashScreen>();

                                  var splash = _container.Resolve<SplashScreen>();
                                  _eventAggregator.GetEvent<AppInitCompleted>().Subscribe(
                                    e => splash.Dispatcher.BeginInvoke((Action)splash.Close),
                                    ThreadOption.PublisherThread, true);

                                  splash.Show();

                                  _splashScreenCreated.Set();
                              }));

            Dispatcher.Run();
        }
```

**Comment by bobdog1986** [comment]
试试await Task.Factory.StartNew()，看看行吗？
另外，请教这个怎么切换Culture？我有default\en-US\zh-CN三个Resx，怎么设置Culture？

**Comment by SeriousM** [comment]
Closed due stall conversation

**Comment by Enviolet** [comment]
I'm really happy to shove my own implementation of localization into the trash, and use this great solution.

But I'm having this same issue right now.
I even tried to put the whole code into a task that will be disposed after a timeout.
However, even long after the timeout should be over the task is not disposed, as the whole app completely freezes on the line where I set the Culture.

It happens only sometimes and only when starting the app.
