### ISSUE TITLE
Strong signing nuget packages

### ISSUE THREAD

**Issue by mandawah** [SeriousM/WPFLocalizationExtension#106]
Thanks for this wonderful lib.
Could you consider strong-signing nuget packages? 
I need to use it from a strong-signed assembly, and as you know it doesn't work since yours is not signed. Thanks

**Comment by torpederos** [comment]
Hi,
you can use [Strong Name Signer](https://github.com/brutaldev/StrongNameSigner) to do it by your self

**Comment by mandawah** [comment]
Hi,
Yes indeed, thanks. I just thought it would be easier if you signed them. 
Regards.

**Comment by SeriousM** [comment]
Thank you for the hint!
