### ISSUE TITLE
Suggestion: Migration to .NET 4.x

### ISSUE THREAD

**Issue by uldisv** [SeriousM/WPFLocalizationExtension#108]
Hi.
It would be nice if project could be migrated to full .NET 4.x. This would let get rid of accessing additional 2.0 framework.
I'm converting it by hand everytime I download a new version. Haven't had any problems with 4.x so far.

Uldis

**Comment by SeriousM** [comment]
Hi Uldis,

I don't know why you want to convert the solution to .net 4+ because as dot.net works, it's backward compatible by design.
Do you have any issues you want to avoid?

**Comment by gpriaulx** [comment]
.Net 3.5 and less aren't installed by default with Windows 10. Would you accept a pull request that addresses this? Older projects could still of course use older releases of this library.

**Comment by SeriousM** [comment]
I'm currently discussing it with @adragoner here: https://gitter.im/SeriousM/WPFLocalizationExtension

**Comment by SeriousM** [comment]
https://msdn.microsoft.com/en-us/magazine/ee819091.aspx -> Overview of Behavior

>The .NET Framework 4 runtime—and all future runtimes—will be able to run in-process with one another. While we did not back-port this functionality to older runtimes (1.0 through 3.5), we did make sure that 4 and beyond will be able to run in-process with any single older runtime. In other words, you will be able to load 4, 5 and 2.0 in the same process, but you will not be able to load 1.1 and 2.0 in the same process. .NET Frameworks 2.0 through 3.5 all run on the 2.0 runtime and so have no conflicts with one another, as shown in Figure 2.

https://stackoverflow.com/a/2642347/660428
https://www.experts-exchange.com/questions/26111498

I guess it's not necessary to compile against .net 4.
We can discuss the point again if you can name me a few important optimizations that would benefit the extensions execution
