### ISSUE TITLE
unable to set default assembly / dictionary / culture on resourcedictionary

### ISSUE THREAD

**Issue by gpomykala** [SeriousM/WPFLocalizationExtension#109]
Hello,

I am trying to incorporate localization extensions into existing project and I have realized that culture / assembly / dictionary setting can be only set on a Dependency object which means they cannot be set on a ResourceDictionary which stores shared templates.

Is there any known workaround for such scenario to avoid using fully classified resource names within ResourceDictionary?

**Comment by SeriousM** [comment]
Hi! Because the ResourceDictionary don't have a link to the visual root it's impossible to set the default assembly in xaml. however, you can set it code behind.
did that work for you?

**Comment by gpomykala** [comment]
Yes, that worked. Thanks!
