### ISSUE TITLE
no code signed package available on NuGet

### ISSUE THREAD

**Issue by gpomykala** [SeriousM/WPFLocalizationExtension#110]
Hello,
Would you consider publishing code signed package on NuGet?

**Comment by SeriousM** [comment]
Hi gpomykala, No.

But you can add the package https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/ to your dependencies and it will sign your assemblies during build time for free.
Or you can simply use https://github.com/brutaldev/StrongNameSigner/releases and sign it yourself.

Cheers

**Comment by gpomykala** [comment]
Well, CodeSigner comes at a cost of signing all the packages before project build which is not sustainable in a bigger solution. thanks for your feedback anyway.

Cheers

**Comment by SeriousM** [comment]
We sign our third party packages ourselves and run an own nuget server for
just that purpose.
Nuget.org does have a free server for that.

Am 06.09.2016 10:29 schrieb "gpomykala" <notifications@github.com>:
