### ISSUE TITLE
EnumRun missing from the NuGet package

### ISSUE THREAD

**Issue by superware** [SeriousM/WPFLocalizationExtension#112]
EnumRun seems to be missing (!) from the NuGet package build, is this possible?

**Comment by superware** [comment]
Hi @SeriousM and @MrCircuit, any plans for a new release?

**Comment by superware** [comment]
It also seems that besides EnumRun, EnumComboBox.PrependType is also missing from the NuGet release, any ideas? :|

**Comment by xmedeko** [comment]
Duplicate of #114
