### ISSUE TITLE
Localization of VM bindings

### ISSUE THREAD

**Issue by wowfood** [SeriousM/WPFLocalizationExtension#113]
Asking here as the documentation for binding dos/don'ts doesn't appear to be working, so not really sure where else to look.

Having an issue with localizing text via binding.  example.

I have my resources stored in a UIResource project, and my resx is called resources.  Key is button_text.

VM has a text property called ButtonText (set to button_text).  and my xaml has 

```
<UserControl x:Name="UserControl"
             xmlns:lex="http://wpflocalizeextension.codeplex.com"
             lex:LocalizeDictionary.DesignCulture="en"
             lex:ResxLocalizationProvider.DefaultAssembly="UIResources"
             lex:ResxLocalizationProvider.DefaultDictionary="Resources">
        <Button
                Command="{Binding Command}"
                Tag="{lex:BLoc ButtonText}" />
</usercontrol>
```

But instead of fetching a translation for ButtonText, I'm getting a blank button.  I'm struggling to find any documentation on how to use BLoc correctly, so any help would be appreciated.  

I've also tried with 

Tag="{lex:BLoc UIResources:Resources:Text}"> but get the same result.

I do have an alternate solution where I'm translating in the codebehind and just performing a normal binding, but I'm unsure how to make that version update when the culture changes.

**Comment by UeliHilfiker** [comment]
Use the [Button.Content](https://msdn.microsoft.com/en-us/library/system.windows.controls.contentcontrol.content(v=vs.110).aspx) property, not Tag. 

So, in your example:
`<Button Command="{Binding Command}" Content="{lex:BLoc ButtonText}" />`
or
`<Button Command="{Binding Command}" Content="{lex:Loc ButtonText}" />`

**Comment by wowfood** [comment]
Using the tag property as part of a style on the button tag sets button text.  With direct text, or just using a normal binding the text displays correctly, setting the text in the tag property shouldn't stop the lex:BLoc from working.

**Comment by SeriousM** [comment]
Closed due stall conversation
