### ISSUE TITLE
NuGet packages are out of date

### ISSUE THREAD

**Issue by adragoner** [SeriousM/WPFLocalizationExtension#114]
Could you please update NuGet packages to the latest version?

**Comment by SeriousM** [comment]
@mrcircuit is able to create the packages because I can't build them right
now. Could you please? Maybe we can find a way to make this process easier?

Am 12.02.2017 22:20 schrieb "Waspy" <notifications@github.com>:

**Comment by superware** [comment]
@MrCircuit can you please update the NuGet package? will be highly appreciated, thanks.

**Comment by adragoner** [comment]
Any updates, guys?

**Comment by superware** [comment]
@SeriousM Can you please update the NuGet package to the latest version?

We would greatly appreciate it.

**Comment by SeriousM** [comment]
I guess I can't help you because my machine is not able to build the whole
project.
For example windows phone and silverlight  support would be dropped.

If that is no issue, I could publish a new major version.

**Comment by superware** [comment]
@SeriousM can you please publish a new major version? if someone will want the phone/silverlight support he might temporarily target the previous versions (for now). Thanks!

**Comment by adragoner** [comment]
@SeriousM I have cleaned up remove_sl_wp (forked) branch, migrated project to the new format and generated NuGet package (2.3.3). I can upload it, but I'll need an API key. What's the procedure like?

**Comment by SeriousM** [comment]
hi @adragoner, thank you very much for your participation!
to keep the source in this repository, you could send a PR from your fork onto this master and then we release it.

**Comment by adragoner** [comment]
@SeriousM Would you like me to sync with master or remove_sl_wp first?

**Comment by SeriousM** [comment]
@adragoner please have a chat at Join the chat: https://gitter.im/SeriousM/WPFLocalizationExtension . This is easier for the following steps

**Comment by adragoner** [comment]
NuGet package (3.0.0) is available now. Issue closed.
