### ISSUE TITLE
Performance issue in design time

### ISSUE THREAD

**Issue by kszabolcs** [SeriousM/WPFLocalizationExtension#115]
Hi,

I have just installed and tried WPF Localization Extension. Everything is ok, but when I change something in the XAML code, after a rebuild the XAML designer freeze the Visual Studio.  I have only one Window (MainWindow), and in this UI has 30 localized text ({lex:Loc Key=xxx}). In this UI, the XAML Designer will work more than 2 minutes, and until this time, I can't do nothing in Visual Studio. I use Visual Studio 2015 Enterprise.

Do you have any idea what can I do? Maybe I didn't set something properly.

Thanks
Szabolcs

**Comment by xmedeko** [comment]
Are you sure it's cause by the WPFLocalizationExtension? Just try the experiment: remove `lex:Loc` and `xmlns:lex` form your code. Do various editing in the XAML then. Do you experience the VS is faster?

**Comment by SeriousM** [comment]
Closed due stall conversation
