### ISSUE TITLE
Initial localization is ignored

### ISSUE THREAD

**Issue by Markus-Rennings** [SeriousM/WPFLocalizationExtension#116]
Setting the langue to a specific culture at startup is ignored due to a bug in :

'private static void SetCultureFromDependencyProperty(DependencyObject obj, DependencyPropertyChangedEventArgs args)
        {
            if (!Instance.GetIsInDesignMode())
                return;'
I think i should be:
'            if (Instance.GetIsInDesignMode())
                return;'

The ! is wrong. It shoud do nothing in DesignMode and change the languange in RuntimeMode.

**Comment by SeriousM** [comment]
@mrcircuit, can you confirm?

Am 14.03.2017 10:41 vorm. schrieb "Markus Rennings" <
notifications@github.com>:

**Comment by Markus-Rennings** [comment]
Sorry it was my fault. The property is only for Design time and works correct
