### ISSUE TITLE
MVVM binding 

### ISSUE THREAD

**Issue by nithinshiriya** [SeriousM/WPFLocalizationExtension#117]
I am trying to bind a property called ["SampleName"]  that is declared in ViewModel.  Here SampleName is key.  However, when trying below code, it display's empty. 

`<TextBlock FontSize="14" Text="{lex:BLoc Value=SampleName}" lex:ResxLocalizationProvider.DefaultAssembly="SAS.Resources" lex:ResxLocalizationProvider.DefaultDictionary="Report" HorizontalAlignment="Center" VerticalAlignment="Top" TextDecorations="Underline" FontWeight="DemiBold" Grid.Row="0" Grid.ColumnSpan="{Binding Path=SpanCount}" Grid.Column="0"/> `

Please suggest me.

**Comment by nithinshiriya** [comment]
@SeriousM

**Comment by wowfood** [comment]
Very late, and not the best fix for your problem, but here's how I've solved it on my end.

Create a translation service along the following lines.
    public class TranslationService : ITranslationService
    {
        private string Translate(
            string id )
        {
            string uiString;

            var locExtension = new LocTextExtension
            {
                Key = "XXX.UI.Resources",
                ResourceIdentifierKey = id
            };
            locExtension.ResolveLocalizedValue( out uiString );

            return uiString ?? id;
        }

In your controls with the databound text value, subscribe to a resource updated message which gets fired off when culture is changed.  Then test the text as

SampleName = TranslationService.Translate( ID );

Do the same in the message subscription so it translates when it gets updated.

It's far from the best solution, but was the only thing I could get working.

**Comment by brunoalreis** [comment]
Hi,

I posted this on so, related to this question: https://stackoverflow.com/a/44030897/1582065

**Comment by wowfood** [comment]
Another belated reply as I've just found an even easier way around this.

`        
<ContentControl x:Class="ASM.DEK.Rome.UI.Controls.Common.Views.CommandButton"
                xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                xmlns:lex="http://wpflocalizeextension.codeplex.com"
                lex:LocalizeDictionary.DesignCulture="en"
                lex:ResxLocalizationProvider.DefaultAssembly="ASM.DEK.Rome.UI.Resources"
                lex:ResxLocalizationProvider.DefaultDictionary="Resources">
    <Canvas>
        <lex:LocProxy Source="{Binding Path=Text, Mode=OneTime}"
                      x:Name="Proxy" />
        <Button Content="{Binding Result, ElementName=Proxy}" />
    </Canvas>
</ContentControl>
`

This seems to be the correct way of doing this.  

@SeriousM I think this issue can probably be closed.  At the same time I think another may need to be raised to update the readme since a lot of this stuff isn't covered unless you delve into it yourself.

**Comment by SeriousM** [comment]
> At the same time I think another may need to be raised to update the readme since a lot of this stuff isn't covered unless you delve into it yourself.

@wowfood could you send an update to the readme please? I'm very very busy at the moment :(
