### ISSUE TITLE
CodePlex shutdown - Move CodePlex documentation to wiki here

### ISSUE THREAD

**Issue by UeliHilfiker** [SeriousM/WPFLocalizationExtension#119]
@MrCircuit 

See shutting down notice in this [blog entry](https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/).

And there is a [walkthrough](https://codeplex.codeplex.com/wikipage?title=Migrating%20to%20GitHub) for migration from Codeplex to github.  See section "License, Documentation, and Home" to migrate the documentation/wiki to github wiki. 

and look this blog article too "[Migrating Wiki content from CodePlex to GitHub](https://peterfoot.net/2017/04/29/migrating-wiki-content-from-codeplex-to-github/)"

It would be cool, if the CodePlex-documentation is migrated, before CodePlex is shutting down...

**Comment by xmedeko** [comment]
Even after the December 15th, 2017, the CodePlex content will be accessible as read-only archive.

I offer my hand with the documentation migration to GitHub Wiki.

**Comment by adragoner** [comment]
Done.
