### ISSUE TITLE
Namespace problem after upgrading to version 3.1.0

### ISSUE THREAD

**Issue by dprevato** [SeriousM/WPFLocalizationExtension#131]
After upgrading to new version 3.1.0, I'm facing a pretty serious problem: first of all, I have errors "The name LocalizeDictionary does not exists in the namespace 'http://wpflocalizeextension.codeplex.com'", and the same message comes from ResxLocalizationProvider. Next, I have the error message "The name 'Loc' does not exists in the namespace 'http://wpflocalizeextension.codeplex.com'".
Needless to say, all went perfectly well before the upgrade (using Nuget Package Manager), and I have no idea about what I possibly have done wrong.

**Comment by xmedeko** [comment]
3.1.0 Works fine for me. Try to clear your build, manually delete all `obj` dirs and all `packages\WpfLocalizeExtension*`.

**Comment by dprevato** [comment]
So I did, and now it works :) thank you very much!
