### ISSUE TITLE
Possible to omit "default" resource files?

### ISSUE THREAD

**Issue by sherman89** [SeriousM/WPFLocalizationExtension#132]
Hey!

First of all thank you very much for this project!

Is it possible to have resources for different cultures, without having a default resource file, using the default provider?

The application supports a specific set of languages, and by default I will choose "en-US", so I only need to have "Strings.en-US.resx", but unless I also add "Strings.resx" which contains the same values as the en-US resource file, I get weird behavior (list only has InvariantCulture and the rest of the cultures are ignored).

Can I force the Localization Extension to use "Strings.en-US.resx" as the default resource, as if it were called "Strings.resx"?

Sorry if this has already been answered, but I didn't find any documentation or answers about this. I'd rather not create a custom provider for this, and I don't like having 2 resource files with the same values.

Thank you!

**Comment by xmedeko** [comment]
The RESX files are .NET standard, they are not specific to this project, e.g. see https://docs.microsoft.com/en-us/dotnet/framework/resources/ or other .NET docs. The advantage is, that you can easily access them from the C# code, too. And, that's what this project do as well - it just reads the RESX files by the standard [`ResourceManager`](https://msdn.microsoft.com/en-us/library/system.resources.resourcemanager(v=vs.110).aspx).
So, you can create own subclass of `ResxLocalizationProvider` and override `GetObject` to make a custom resources reading. But I *strongly* recommend you to go with the .NET standard.

**Comment by sherman89** [comment]
I read about ResourceManager and apparently those "default" files are required and should not be deleted. I guess I'll just copy the contents of "en-US" to them every time via some script or something.

Thank you for the answer! :)

**Comment by xmedeko** [comment]
You can move "en-US" files to default ones, you do not need to have a copy.

**Comment by sherman89** [comment]
I thought about that, but then I would lose the choice for "English (United States)" from MergedAvailableCultures, which I thought was nice and eliminated the need to manually manage a list of available cultures.

Should I just maintain my own list of supported cultures?

Thanks.

**Comment by xmedeko** [comment]
Hm, do not know much about `MergedAvailableCultures`. Maybe better to create your own, e.g. copy `MergedAvailableCultures` and add/remove what you need.

**Comment by sherman89** [comment]
Actually yeah, I could just copy it and then add "en-US" myself... d'oh!

I think we've reached the conclusion of this thread, thank you very much for your responses xmedeko! 👍
