### ISSUE TITLE
I need to be informed about Culture changed

### ISSUE THREAD

**Issue by ThomasHelm** [SeriousM/WPFLocalizationExtension#134]
I have a ListBox for changing the Culture at Runtime. If user changes the Culture, the next time the application starts Culture should be that changed Culture.

```xml
<ListBox
    ItemsSource="{Binding Source={x:Static lex:LocalizeDictionary.Instance},
    Path=MergedAvailableCultures}"
    SelectedItem="{Binding Source={x:Static lex:LocalizeDictionary.Instance}, Path=Culture}"
    DisplayMemberPath="NativeName"
```

In the comment to the Cultere property I have found: "Gets or sets the System.Globalization.CultureInfo for localization. On set, WPFLocalizeExtension.Engine.LocalizeDictionary.DictionaryEvent is raised."

But here is the Problem: the `DictionaryEvent` is `internal`, also the `AddListener()` and `RemoveListener`. `DictionaryEvent`, `AddListener()` and `RemoveListener` has to be `public`.

**Comment by sherman89** [comment]
You'll need to save the CultureInfo on the disk if you want to set it again after re-starting the program.

You can save it as a [user setting](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/using-application-settings-and-user-settings) then read that value in app.xaml.cs and use it to set LocalizeDictionary.Instance.Culture.

**Comment by ThomasHelm** [comment]
Thanks for your reply. I was a litle bit inaccurate with the description.

In the moment I wrote the question I have forgotten that I have some Texts which must be translated by code. That is the actual use case.

**Comment by sherman89** [comment]
I just took a quick look at the source code, and it looks like the PropertyChanged event is raised for the Culture property, so you can simply do this to detect culture change:
```
LocalizeDictionary.Instance.PropertyChanged += (sender, args) =>
{
    if (args.PropertyName == nameof(LocalizeDictionary.Instance.Culture))
    {
        // do something ...
    }
};
```

Goodluck! :)

**Comment by ThomasHelm** [comment]
The approach with `PropertyChanged` works.

I think I was too close to the `DictionaryEvent`, but why is there an `public Interface IDictionaryEventListener` and how is it to use without the `DictionaryEvent`?

Thanks
