### ISSUE TITLE
WPFLocalizeExtension and AssemblyResolve

### ISSUE THREAD

**Issue by Mitsoshima** [SeriousM/WPFLocalizationExtension#135]
We are just beginning to use the WPFLocalizeExtension in a project. It works, but it has a serious impact on the startup performance of the app. It tries to load the resources for all possible languages, including many which we won't ever provide resources for. Normally that might happen without notice, but in this case we have a special folder structure for some of the loaded assemblies. Although the resource DLLs are still situated in language folders directly beneath the folder of the executable, but the app gets an AssemblyResolve event for every language.

Thanks for your help in advance.

**Comment by Mitsoshima** [comment]
Got it:
When you have a look at the code, you will find a class called ResxLocalizationProviderBase. This class includes a method GetResourcemanager, which causes the massive amounts of AssemblyResolve events, because it tries to get the resource set of all cultures that ship with the .NET Framework.
We modified the code by creating a list of CultureInfo objects, that includes only languages, we'd like to provide resources for.

**Comment by xmedeko** [comment]
Can you describe the changes you have made?
