### ISSUE TITLE
Design time text in Window.Title not working

### ISSUE THREAD

**Issue by Urganot** [SeriousM/WPFLocalizationExtension#137]
Hi,

I've got the following error if I try to use lacalization in the window title:

![image](https://user-images.githubusercontent.com/5991022/37766863-899828f8-2dc8-11e8-847c-25d15a8dd996.png)

This is my xaml:
`<Window
        xmlns:lex="http://wpflocalizeextension.codeplex.com"
        lex:LocalizeDictionary.DesignCulture="en"
        lex:ResxLocalizationProvider.DefaultAssembly="AssemblyName"
        lex:ResxLocalizationProvider.DefaultDictionary="Strings"     
        mc:Ignorable="d" 
        Title="{lex:Loc RenameLabelTitle}" Height="171.331" Width="411.97" ResizeMode="NoResize">
    <Grid>***</Grid>
</Window>`

It works if I run it but Visual Studio shows an error :
![image](https://user-images.githubusercontent.com/5991022/37766958-da9fa140-2dc8-11e8-8ce4-8f07ea92f9dc.png)

The windows' properties shows:
![image](https://user-images.githubusercontent.com/5991022/37767037-0d78678c-2dc9-11e8-824b-933485bce34b.png)

Any idea of how to fix this?

**Comment by Urganot** [comment]
I'm using Visual Studio 2017.
When I open my solution is Blend VS 2017 it work in both.

**Comment by xmedeko** [comment]
Duplicate to #136.

**Comment by Urganot** [comment]
I'm not sure if this is a duplicate.
Additionally to not displaying the missing text text it also cant find the resource string

**Comment by xmedeko** [comment]
Yes, the #136 is about to get rid of the error and display "Key: RenameLabelTitle" if the resource cannot be found.
Do you see the title when you run the app? If so, try to open/close XAML, open/close project, recompile project. As the last resort, close the VS, remove `obj/` and `bin/` dirs and open VS again. The designer uses some sort of caching. I do not know it well. I do not use designer, one reason is these kind of problems.
