### ISSUE TITLE
Add StrongName

### ISSUE THREAD

**Issue by PArns** [SeriousM/WPFLocalizationExtension#141]
It would be awesome if the extension could be Strong Name signed, so it's also usable in an Strong Named envionment

**Comment by xmedeko** [comment]
StrongName? Hey, it's 2018 ...
E.g. see https://github.com/MahApps/MahApps.Metro/issues/3029

**Comment by SeriousM** [comment]
Thank you @xmedeko 👍

**Comment by konne** [comment]
@Jehoel at the moment 100% of the maintaner think not to sign this.
If you need signing just use: https://github.com/dsplaisted/strongnamer
This works great and we use it also in one of our projects. I will lock this issue.

**Comment by xmedeko** [comment]
I have to admit, that the MahApps project (my source of wisdom) has changed their approach and started to release strong named assemblies, see https://github.com/MahApps/MahApps.Metro/issues/3339 (also @Jehoel's request :-).

**Comment by konne** [comment]
The only approach that I think could be okay to have 2 nuget packages (signed / unsigned)
1. to don't break things like MahApps
2. to give the users still the change.
I have logged this as #156
