### ISSUE TITLE
Provide Localization providers Examples

### ISSUE THREAD

**Issue by urza** [SeriousM/WPFLocalizationExtension#25]
Could you please provide working example solution (simple wpf project) featuring custom Localization provider? There is some class CSVProvider in source code, but I was not able to use it tu successfully localize my project. I have internal dictionary of key/value pairs that will be my provider. Thanks a lot.

**Comment by ThomasHelm** [comment]
I can change the provider to a provider off my application at runtime with
```
LocalizeDictionary.Instance.DefaultProvider = Providers.LangTextProvider.Instance;
```

How do I this for Design Time???
