### ISSUE TITLE
Drop Support for WP7 / Silverlight

### ISSUE THREAD

**Issue by SeriousM** [SeriousM/WPFLocalizationExtension#28]
yes, thats right. WP7 is dead and Silverlight felt into the darkness. 
why now? we can't build WP7 anymore and silverlight doesn't make any sense anymore. 

What do you think?

Reference: https://wpflocalizeextension.codeplex.com/workitem/9315

**Comment by MrCircuit** [comment]
WP7: OK
SL: No - it still is used in productive environments (e.g. by myself :-))

**Comment by SeriousM** [comment]
> SL: No - it still is used in productive environments (e.g. by myself :-))

then you have to maintain it :)


# SOLUTION

we'll drop WP7 support

**Comment by MrCircuit** [comment]
**I will** hehe
Please read my edit! It is not WP7 alone - you would drop also WP8 and WP8.1 support!

**Comment by SeriousM** [comment]
well then, you have to support it. i don't have any access to windows phones and no clue what problems they have. is that ok for you @MrCircuit ?
