### ISSUE TITLE
AvalonDock Headers Title Binding not working with Localization

### ISSUE THREAD

**Issue by alvarojosepl** [SeriousM/WPFLocalizationExtension#33]
I am using avalondock as a framework, and i am using WPFLocalization for Localization of course hehe.

The fact is when i try to bind the Header Title property by:
Title="{lex:Loc myResourceName}"

It actually dosnt display the output it, it will display:
Key: myResourceName

Probably has to do with some interaction happening in between both frameworks.

 I would like to know if there is any workaround, make a resource out of the lex that i could actually imput in my property? how can this be implemented?

**Comment by MrCircuit** [comment]
In an old project of mine, I used the viewmodels to set the title of the avalondock windows:

<ad:DockingManager.LayoutItemContainerStyle>
                <Style TargetType="{x:Type ad:LayoutItem}">
                    <Setter Property="Title" Value="{Binding Model.Title}" />
...

Then I used the extension in the viewmodel constructor like this (assuming the VM has a Title property):

var ext = new LocExtension("assembly:dict:key");
ext.SetBinding(this, GetType().GetProperty("Title"));
