### ISSUE TITLE
Design-time issue in Visual Studio 2013 (WPF)

### ISSUE THREAD

**Issue by sindrepm** [SeriousM/WPFLocalizationExtension#34]
Hello,

First, let me say that I think this extension is great and is working very well on runtime. However, I have one issue currently with the design-time support in Visual Studio 2013 on my WPF project. I am using the ResxLocalizationProvider.

The texts from the resource file does not show up in the designer until after I restart Visual Studio. I added a simple string to the Text property of a TextBlock like this:

`<TextBlock Text="{lex:Loc MyString}"></TextBlock>`

However, the designer shows "Key: MyString" for the label (I have tried to rebuild the project). After restarting Visual Studio it pulls the string from the resource file and shows the value of MyString.

Everything works fine at runtime, so I think there is nothing wrong with my syntax. I have also tried to change the value of `LocalizeDictionary.DesignCulture` without any effect.

Is this a known bug or do you have any suggestions on how to fix it?

Also, secondly I would like to ask if it is possible to get intellisense/strongly-typed resource keys? I think that would be a great feature. Compile-time checking of keys would also be great. Any plans for it?

Thank you,
Sindre

**Comment by MrCircuit** [comment]
Hi.
I've already managed to get external assemblies to work in the designer as expected (added or changed keys are reflected after recompile, language switching with DesignCulture). Unfortunately, I was not able to get the same behaviour for the main assembly's resources. I don't know exactly, but I think it might be the designer that cannot unload the old main assembly's resources and load new resources. I've already tried a couple of hours to find a solution but without success. Has anybody an idea how to solve this issue?

**Comment by SeriousM** [comment]
:+1: very well done!

**Comment by Cuiyansong** [comment]
I meet the same problem, sometime it can render "strings" and the other  side it just show an error of "does not have a resource identified by the URI XXX". I tried to find the problem for a few days, but still not have a solution. Mybe it just like @MrCircuit said, " I think it might be the designer that cannot unload the old main assembly's resources and load new resources", sometimes it cannot load right assembly and dictionary which in the xaml header, so strange! I will continue to concern.

**Comment by MrCircuit** [comment]
Any update on this topic?

**Comment by joelbourbon** [comment]
Hey @MrCircuit !

Just added your Nuget package to a solution I have to localize. Everything seems to work fine at runtime but I get exactly the same issue as the other guys here at design time. In the designer, the strings are not reloaded when edited in the resx file. The string switches when I change the LocalizeDictionary.DesignCulture but it keeps the values loaded the first time.

Ex: I'm switching from English(EN) to French (FR). 
At first test:
TestString (EN) = "Hello World"
TestString (FR) = "Bonjour le monde"
In the designer before I reboot Visual Studio, it shows Key: TestString.

After first reboot:
The string are loaded properly even when switching between languages.
I change TestString (FR) to : "Bonjour le monde !!!!!"
After rebuild, close .xaml and reopen .xaml --> Still shows "Bonjour le monde"

After reboot --> shows "Bonjour le monde !!!!!"

Thanks for the follow up !

**Comment by MrCircuit** [comment]
Thanks for the hint.
I'll see if we can use it.

**Comment by Cuiyansong** [comment]
When I attached the visual studio IDE and the other vs open "MainWindow.xaml", I got the fellowing message, does someone have suggestions? 

System.TypeLoadException was caught
  HResult=-2146233054
  Message=Could not load type 'XAMLMarkupExtensions.Base.DependencyObjectHelper' from assembly 'XAMLMarkupExtensions, Version=1.1.6.3, Culture=neutral, PublicKeyToken=null'.
  Source=WPFLocalizeExtension
  TypeName=XAMLMarkupExtensions.Base.DependencyObjectHelper
  StackTrace:
       at WPFLocalizeExtension.Extensions.LocExtension.FormatOutput(TargetInfo endPoint, TargetInfo info)
       at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
       at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
       at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue()
       at WPFLocalizeExtension.Extensions.LocExtension.ResourceChanged(DependencyObject sender, DictionaryEventArgs e) in g:\Code\GitHub\Hearthstone-Deck-Tracker_UITranslation\WPFLocalizationExtension-master\WPFLocalizeExtension\Extensions\LocExtension.cs:line 318
  InnerException:

**Comment by eBeyond** [comment]
Hi,

is there some progress on this issue? It's really annoying to refresh the project all the times and my impression is that's not solving the problem on a regular basis. Sometimes it's resolved sometimes it's not.

**Comment by eBeyond** [comment]
Hmmm,

I've tried it with VS 2015 RC... It's the same as in VS 2013.

**Comment by xmedeko** [comment]
I ahve the same issue. I chaneg RESX files and do not see texts in the designer. But after some time working in Studio the text appears in the designer and even switching `DesignCulture` works well. I've tried to discover, what triggers the change but cannot find it (rebuild, unload load project or solution, nothing works). Maybe some cache which has to timeout?

**Comment by mgnslndh** [comment]
Is this problem related to the ResXLocalizationProvider only or will we run into the same issue for any provider? How about known workarounds?

**Comment by aconcagua21** [comment]
Hi, thanks for nice work!
I have modular MVVM application. Resource lookup works well both in design and run time. However, when I switch the language, only controls from the main assembly get switched. Other resources remain in the original language. What am I missing?
Thanks,
Jiri

**Comment by UeliHilfiker** [comment]
@aconcagua21 
Set the language for every form/window manually, see: https://github.com/SeriousM/WPFLocalizationExtension/issues/66

**Comment by redplane** [comment]
Does anyone know this has been resolved or not ? 
I'm having the same issue in VS 2017

**Comment by UeliHilfiker** [comment]
I have to compile the project and reopen Visual Studio 2017 to see the final and proper result in designer.

**Comment by konne** [comment]
the designtime support is tricky and works not in all cases, this ticket ist closed
