### ISSUE TITLE
Default Assembly and Dictionary

### ISSUE THREAD

**Issue by alexdrenea** [SeriousM/WPFLocalizationExtension#35]
More of a comment than an issue, regarding the way we make use of the assembly and dictionary properties.

Trying to use the (new) library (I've used it since since its initial release a long long time ago), I realized that in every xaml file I have to declare the default assembly and default dictionary, in the top level control, then I could use the markup extension without additional parameters. Going through the code and comments, I realized that that's required because you do a search from the current element up the visual tree until you find a parent that defines those properties and use them. 
This is indeed really nice and gives you flexibility to have your resources scattered around assemblies and files.

The way I wanted to implement localization, was to have all my resources in one assembly and potentially in one or two resource files  (one for strings, one for images). This makes the need to always declare the assembly and dictionary a bit cumbersome.
This being said, I was hoping that I could declare the the default assembly and default dictionary at the resx localization provider level and then those would be available from any xaml file where I use them without the need to declare them again at the parent level. However, if you do declare them at any point in the Visual Tree, those values would be used, and not the defaults.

The change is relatively simple, just modify the GetAssembly and GetDictionary methods to use the instance's values if everything else fails. I have already done this in my local repo and I can create a pull request if you feel this is something worth doing and does not break any other patterns I did not notice.

* A further improvement would be the ability to define default assembly and dictionary per type (i.e. one for strings, one for images, one for other localizable elements). I did not get that far into the code to figure how this can be achieved (if possible).

**This would also fix issue #31 and #26 because if Visual Tree search fails to find the assembly and dictionary, we just use the default ones.

**Comment by MrCircuit** [comment]
This issue was handled as proposed by you (pull-request #37). Thanks for your input.
