### ISSUE TITLE
Fluent.Ribbon backstage localization issue using with PRISM and MEF

### ISSUE THREAD

**Issue by dymanoid** [SeriousM/WPFLocalizationExtension#36]
Hello,

first of all I would like to thank you for this really nice localization feature. We're using it in our product and are fully satisfied with the result!

However, we're now encountering an issue using an open source WPF ribbon control called Fluent.Ribbon (see https://fluent.codeplex.com/).

The problem is that the ribbon's backstage gets not localized with WPF localization extension when using them in a complex scenario (Microsoft PRISM and Microsoft.Composition MEF2 dependency injection container). I've created an issue for that control, but the developers team mean this is not really a Fluent.Ribbon issue.

Please check this issue at codeplex: https://fluent.codeplex.com/workitem/22516
Here you can download a small VS2012 test solution which shows the issue. Furthermore, in a last comment there is an explanation made by the Fluent developer team why it doesn't work.

Could you please check this out and give me a feedback? Perhaps there is a workaround which we could use in our product to get the ribbon's backstage localized?

Thank you in advance!

**Comment by MrCircuit** [comment]
I also use Fluent "fluently" :-). I will have a look on that issue.
