### ISSUE TITLE
Basic example not working

### ISSUE THREAD

**Issue by DoctorVanGogh** [SeriousM/WPFLocalizationExtension#40]
I'm trying to use your library to localize a project, but can't seem to get it to work.

Even using a simplified WPF test project called 'Foo' I get this error both at design and run time:

> Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure ".\Properties\Resources.resources.resources" was correctly embedded or linked into assembly "Foo" at compile time, or that all the satellite assemblies required are loadable and fully signed.

This is the whole of my glorious test window:
```<Window x:Class="Foo.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:lex="http://wpflocalizeextension.codeplex.com"
        lex:LocalizeDictionary.DesignCulture="en"
        lex:ResxLocalizationProvider.DefaultAssembly="Foo"
        lex:ResxLocalizationProvider.DefaultDictionary="\Properties\Resources"
        Title="MainWindow" Height="350" Width="525">
    <Label Content="{lex:Loc Bar}"/>   
</Window>```
The Designer shows the label's content as 'Key: Bar'. The `lex:ResxLocalizationProvider.DefaultAssembly="Foo"` part of the xaml has squigly underlines with the above error as tooltip.

No idea what is going so completely wrong here (I'm guessing the double '.resources' extension is *not* supposed to happen).

**Comment by MrCircuit** [comment]
* No example supplied
* Most probably related to #34
