### ISSUE TITLE
Threading issue

### ISSUE THREAD

**Issue by Rand-Random** [SeriousM/WPFLocalizationExtension#42]
Hi.

I have a little annoying problem with opening new windows in separate threads, have a look at the following setup.

This is my Window XAML:
```
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:lex="http://wpflocalizeextension.codeplex.com"
        x:Class="WpfApplication1.Window1"
        Height="100"
        Width="100"
        lex:LocalizeDictionary.DesignCulture="de">
    <StackPanel Orientation="Vertical">
        <Button Click="NewWindowHandler"
                Content="newwindow"></Button>
        <TextBlock Text="{lex:Loc WpfApplication1:Strings:HelloWorld}"></TextBlock>
    </StackPanel>
</Window>
```
And this is the code behind:

```
private void NewWindowHandler(object sender, RoutedEventArgs e)
{
    Thread newWindowThread = new Thread(new ThreadStart(ThreadStartingPoint));
    newWindowThread.SetApartmentState(ApartmentState.STA);
    newWindowThread.IsBackground = true;
    newWindowThread.Start();
    newWindowThread.Join();
}

private void ThreadStartingPoint()
{
    Window1 tempWindow = new Window1();
    tempWindow.Closed += tempWindow_Closed;
    tempWindow.Show();
    System.Windows.Threading.Dispatcher.Run();
}

private void tempWindow_Closed(object sender, EventArgs e)
{
    (sender as Window).Dispatcher.InvokeShutdown();
}
```

When you run this application and hit the button you will notice that no second window shows up, if you remove the line lex:LocalizeDictionary.DesignCulture="de" the window will show.

Another issue I am facing is a little more complicated.
Imagine you have 3 windows.
1. Window - is the main window application starts with it
2. Window gets opened in a separate thread
3. Window gets opened after 2nd Window gets closed in the UI thread again, this window also has a UserControl in it

Upon opening the 3rd Window with the usercontrol application crashes telling me I am accessing something from a different thread.

This is the code to reproduce:
(Notice that Window2/3 and UserControl have nothing is codebehind)
(To reproduce you have to hit the button in Window1 2 times - 1 hit opens Window2 and than Window3 - Window3 will cause the crash)

Window1 XAML:
```
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:lex="http://wpflocalizeextension.codeplex.com"
        x:Class="WpfApplication4.Window1"
        Height="200"
        Width="200">
    <StackPanel Orientation="Vertical">
        <Button Click="NewWindowHandler"
                Content="newwindow"></Button>
        <TextBlock Text="{lex:Loc WpfApplication4:Strings:HelloWorld}"></TextBlock>
    </StackPanel>
</Window>

```

Window1 Code Behind:
```
private int _counter = 0;
private void NewWindowHandler(object sender, RoutedEventArgs e)
{
    _counter++;

    if (_counter == 1)
    {
        var newWindowThread = new Thread(OpenWindow2);
        newWindowThread.SetApartmentState(ApartmentState.STA);
        newWindowThread.IsBackground = true;
        newWindowThread.Start();
        newWindowThread.Join();
        return;
    }

    if (_counter == 2)
    {
        OpenWindow3();
        return;
    }

    Application.Current.Shutdown();
    return;
}

private void OpenWindow2()
{
    var tempWindow = new Window2();
    tempWindow.Closed += tempWindow_Closed;
    tempWindow.Show();
    System.Windows.Threading.Dispatcher.Run();
}

private void OpenWindow3()
{
    var tempWindow = new Window3();
    tempWindow.Show();
}

private void tempWindow_Closed(object sender, EventArgs e)
{
    (sender as Window).Dispatcher.InvokeShutdown();
}
```

Window2 XAML:
```
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:lex="http://wpflocalizeextension.codeplex.com"
        x:Class="WpfApplication4.Window2"
        Height="200"
        Width="200">
    <StackPanel Orientation="Vertical">
        <TextBlock Text="{lex:Loc WpfApplication4:Strings:HelloWorld2}"></TextBlock>
    </StackPanel>
</Window>
```

Window3 XAML:
```
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:lex="http://wpflocalizeextension.codeplex.com"
        xmlns:wpfApplication4="clr-namespace:WpfApplication4"
        x:Class="WpfApplication4.Window3"
        Height="200"
        Width="200">
    <StackPanel Orientation="Vertical">
        <Button Content="newwindow"></Button>
        <TextBlock Text="{lex:Loc WpfApplication4:Strings:HelloWorld3}"></TextBlock>
        <wpfApplication4:UserControl1></wpfApplication4:UserControl1>
    </StackPanel>
</Window>
```

UserControl XAML:
```
<UserControl x:Class="WpfApplication4.UserControl1"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             mc:Ignorable="d"
             xmlns:lex="http://wpflocalizeextension.codeplex.com">
    <Grid>
        <Label Content="{lex:Loc WpfApplication4:Strings:HelloWorld}"
               Margin="5"
               Grid.Row="0"
               Grid.Column="0"
               VerticalAlignment="Center"
               Target="{Binding ElementName=txtAccNr}" />
    </Grid>
</UserControl>
```

The things I noticed so far:
1. If Window2 has no lex:loc, Window3 opens
2. If Window3 has no usercontrol it opens

Hope everything is clear.

**Comment by MrCircuit** [comment]
I will first take care of the other (more urgent) issues and then I'll continue with this one.

**Comment by Rand-Random** [comment]
Thanks for the update.

**Comment by MrCircuit** [comment]
Hi - I just want to keep you updated, that this issue will still need some time, because I'm very busy at work right now. I expect to have more time mid of Feb.

**Comment by MrCircuit** [comment]
Hi,

work is in progress on this topic right now. I already figured out what to do to support multiple UI threads. But there's still a huge bug when switching the language :-). Because of this, I'll not push the results yet.

**Comment by Rand-Random** [comment]
Thanks for the update, good luck on the fix. Hope to see it soonish™ :)

**Comment by MrCircuit** [comment]
Good news: I got it working. I had to change the base library (XamlMarkupExtensions). As soon as I made the next release there (this evening), I'll push the changes.

**Comment by SeriousM** [comment]
:clap: :clap: :clap:

**Comment by Rand-Random** [comment]
Going to test it soon, cant wait to get rid of all the Dispatcher.Invoke stuff that I randomly added to please my boss. :)

**Comment by MrCircuit** [comment]
If I missed something, please provide detailed information.
Thanks again for your patience :-).

**Comment by Rand-Random** [comment]
I have now tested the new version.
The exception of my second problem is gone but my first problem is still there.

Not sure if you said its fixed or not since you mentioned the following
"But there's still a huge bug when switching the language :-)"

Got this fixed it the current version?
(I am talking about the problem that if the second-ui-thread-window contains lex:LocalizeDictionary.DesignCulture="de" the application freezes)

**Comment by MrCircuit** [comment]
You're right - this was indeed a problem but I've overseen it during testing. I'll have a look on that.
The huge bug I mentioned had other effects that were solved.

**Comment by KristianKuhlmann** [comment]
This should be fixed as well by the merge of the pull request 74 (https://github.com/SeriousM/WPFLocalizationExtension/pull/74) done to fix issue#56 (https://github.com/SeriousM/WPFLocalizationExtension/issues/56).

**Comment by SeriousM** [comment]
can anyone please confirm that?

**Comment by Rand-Random** [comment]
Tested it with the latest version from trunk and the freeze is gone, thx.

**Comment by SeriousM** [comment]
> Tested it with the latest version from trunk and the freeze is gone, thx.

Glad to hear! Thank you @KristianKuhlmann for the fix!
