### ISSUE TITLE
Problem with CSV example

### ISSUE THREAD

**Issue by evertd** [SeriousM/WPFLocalizationExtension#45]
I'm trying to get the CSV example working cause I would like to write my own provider that uses a database connection and gets values at design time. So I got 2 questions. Is this even possible?

For the CSV example I have the following problem. I uncomment this code in the MainWindow and get the following errors.

lex:LocalizeDictionary.Provider>
  Example:CSVLocalizationProvider FileName="Example" HasHeader="True" />
lex:LocalizeDictionary.Provider>

The specified value cannot be assigned. The following type was expected: "ILocalizationProvider".

I hope somebody can help me. 

Thanks in advance

**Comment by MrCircuit** [comment]
Hi, you are right. The example CSV provider seems to be left behind by the recent development. I'll try to get an example to work with one of the example CSV providers .

**Comment by MrCircuit** [comment]
The CSV provider uses an outdated way to get the running VS process in order to get the design time files. I fixed this in a similar way as already done for resx.

**Comment by evertd** [comment]
Hello,

I was trying the CSV example again and I still go this error

An object of the type "ProviderExample.CSVLocalizationProvider" cannot be applied to a property that expects the type "WPFLocalizeExtension.Providers.ILocalizationProvider". in my xaml...

Does anybody know how to fix this problem? Thanks for the help!

Kind regards

**Comment by MrCircuit** [comment]
Have you tried the last version of the AssemblyTest test project? I tested it right now again and it worked without these errors. Maybe something is missing, e.g. the resource files (you have to enable at least "Copy if newer")?

**Comment by evertd** [comment]
![image](https://cloud.githubusercontent.com/assets/10117416/5896477/800c6268-a536-11e4-9cf6-89c5fe1bc8cd.png)

This is the error I get.
