### ISSUE TITLE
Increase GetResourceManager 'cache' timeout

### ISSUE THREAD

**Issue by Phyxion** [SeriousM/WPFLocalizationExtension#48]
This line:
> if (AppDomain.CurrentDomain.FriendlyName.Contains("XDesProc") && ((now - lastUpdateCheck).TotalSeconds >= 1.0))

In https://github.com/SeriousM/WPFLocalizationExtension/blob/master/WPFLocalizeExtension/Providers/ResxLocalizationProviderBase.cs#L299

The 1 second is way too low when you have a lot of files in your solution. It takes nearly a minute to find all files in my solution. I currently have put it at '60.0' and it's working now without taking 10+ minutes to load a xaml.

**Comment by SeriousM** [comment]
How big is your project?
Could the size be the issue?
@MrCircuit did you noticed such a delay?

**Comment by Phyxion** [comment]
Here are some statistics about my project:
31,7 GB (34.043.961.786 bytes)
77.455 Files, 10.754 Folders

So yes, the size is an issue. Besides the size, I don't see a reason why this should be at one second. It only stresses the disk a lot.

**Comment by MrCircuit** [comment]
This IS a big project :-).
Although, only the files matching the resource assembly name are copied, the search process might take some time.

It's OK for me to change the value to a higher one. The 1s time was just a guess how fast a user expects that changes will be reflected in the designer.

**Comment by SeriousM** [comment]
We build that with test-projects or not-so-large projects in mind. Lets imagine you open a small project and you have to wait 60 seconds until ready.
what about going from 1 second to max 30, depending how long it takes to get ready?
eg. every time it's not ready increase the timeout by 1-2 seconds up to 30.

**Comment by Phyxion** [comment]
Yes, it's big, it's mostly content but as it searches every folder in solution it takes a serious time to complete. Perhaps the locations of the files can be cached instead (https://github.com/SeriousM/WPFLocalizationExtension/blob/master/WPFLocalizeExtension/Providers/ResxLocalizationProviderBase.cs#L321)? I'm not sure how often this changes but even 30 seconds wouldn't cut it with a project this size, it takes nearly a full minute here to find the files. Because the other calls are then instant it works fine. Another idea is to scale the caching timeout based on the number of files on disk (like 1 second for every 1000 files).

@SeriousM, it also doesn't mean you have to wait 60 seconds until it's ready, it's just the caching time. It does take a bit longer until changes are reflected in the designer (the cache timeout), but it's currently completely unusable (VS just freezes for 10+ minutes).

**Comment by MrCircuit** [comment]
One possible approach could really be to cache the results of the file search process. This, in turn, would result in the need to restart the designer / VS in case a resource file was added afterwards. But for "settled" projects that only expect changes in the resource file content, this is OK.

What do you think about this compromise?

**Comment by Phyxion** [comment]
Yeah, that works too, I initially used that instead of increasing the caching timeout.

**Comment by MrCircuit** [comment]
OK, I'll fix that. I even can cache the project directory, once it was found :-). Then this should reduce the overhead even more. Thanks for the hint.

**Comment by MrCircuit** [comment]
Hi,

Sorry for the delay. Now it should work as described above. Could you please test it at your big project before I can close the issue?

**Comment by Phyxion** [comment]
I'll try it out in the next few days and let you know, thanks!

**Comment by Phyxion** [comment]
Sorry for the delay, I just downloaded the latest version through NuGet and I can confirm that it's working flawlessly! Finally a version I can use again that is just 1:1 from NuGet :+1:

**Comment by SeriousM** [comment]
nice to hear that :)
