### ISSUE TITLE
Unit Tests Exception

### ISSUE THREAD

**Issue by HartlD** [SeriousM/WPFLocalizationExtension#50]
Hi,
I'm getting always the followitng exception:
Test Name:	NominalGeometryInputAllTests
Test FullName:	UnitTest_NominalGeometryInput.GeometryInputTests.NominalGeometryInputAllTests
Test Source:	e:\VisualStudio2013\ALC Neu\UnitTest_NominalGeometryInput\GeometryInputTests.cs : line 25
Test Outcome:	Failed
Test Duration:	0:00:00,1824027

Result Message:	Die UnitTest_NominalGeometryInput.GeometryInputTests.NominalGeometryInputAllTests-Testmethode hat eine Ausnahme ausgelöst: System.Windows.Markup.XamlParseException: Zeilennummer "12" und Zeilenposition "30" von "Beim Festlegen der Eigenschaft "WPFLocalizeExtension.Providers.ResxLocalizationProvider.DefaultAssembly" wurde eine Ausnahme ausgelöst.". ---> System.InvalidOperationException: Der aufrufende Thread kann nicht auf dieses Objekt zugreifen, da sich das Objekt im Besitz eines anderen Threads befindet.
Result StackTrace:	
bei System.Windows.Threading.Dispatcher.VerifyAccess()
   bei System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   bei WPFLocalizeExtension.Engine.LocalizeDictionary.GetProvider(DependencyObject obj)
   bei WPFLocalizeExtension.Providers.ParentChangedNotifierHelper.GetValue[T](DependencyObject target, Func`2 GetFunction)
   bei WPFLocalizeExtension.Engine.LocalizeDictionary.GetFullyQualifiedResourceKey(String key, DependencyObject target)
   bei WPFLocalizeExtension.Extensions.LocExtension.FormatOutput(TargetInfo endPoint, TargetInfo info)
   bei XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   bei XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   bei XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue()
   bei WPFLocalizeExtension.Extensions.LocExtension.ResourceChanged(DependencyObject sender, DictionaryEventArgs e)
   bei WPFLocalizeExtension.Engine.LocalizeDictionary.DictionaryEvent.Invoke(DependencyObject sender, DictionaryEventArgs args)
   bei WPFLocalizeExtension.Engine.LocalizeDictionary.ProviderUpdated(Object sender, ProviderChangedEventArgs args)
   bei WPFLocalizeExtension.Providers.ResxLocalizationProviderBase.OnProviderChanged(DependencyObject target)
   bei WPFLocalizeExtension.Providers.ResxLocalizationProvider.AttachedPropertyChanged(DependencyObject obj, DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   bei System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   bei System.Windows.Baml2006.WpfMemberInvoker.SetValue(Object instance, Object value)
   bei MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   bei MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
 --- Ende der inneren Ausnahmestapelüberwachung ---
    bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   bei System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   bei System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   bei System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   bei NominalGeometryInput.ControlLängshöheView.InitializeComponent() in e:\VisualStudio2013\ALC Neu\NominalGeometryInput\View\GeometryInput\ControlLängshöheView.xaml:Zeile 1.
   bei NominalGeometryInput.ControlLängshöheView..ctor(ControlViewModel vm) in e:\VisualStudio2013\ALC Neu\NominalGeometryInput\View\GeometryInput\ControlLängshöheView.xaml.cs:Zeile 10.
   bei UnitTest_NominalGeometryInput.GeometryInputTests.NominalGeometryInputAllTests() in e:\VisualStudio2013\ALC Neu\UnitTest_NominalGeometryInput\GeometryInputTests.cs:Zeile 99.

I also tested it witho Monitor.Lock.

**Comment by MrCircuit** [comment]
Hi,

Please check, at which thread the loc extension was used first in the execution context of the unit test (let's call this the "creator thread"). All access operations to this extension must (right now - refer to #42) be synchronized to this "creator thread" because of the dependency properties of the extension.

**Comment by MrCircuit** [comment]
The issue should be solved by the last release. Please test and comment. Thanks
