### ISSUE TITLE
Designer stops loading custom UserControls

### ISSUE THREAD

**Issue by Joris8** [SeriousM/WPFLocalizationExtension#51]
Hi,
For a project I am trying to integrate the WPFLocalizeExtension in an application.
I have the following setup:
 * The WPF application itself (references to a controls and style dll)
 * Controls DLL (Contains an InputPicker UserControl)
 * Style DLL (Contains the style for the InputPicker UserControl)
Software:
 * Visual Studio 2013 (.NET Framework 4.5.2)

When I run the application without WPFLocalizeExtension it works fine. 
But when I integrate WPFLocalizeExtension and after running it once, the following exception occurs in the designer:
*The component 'CleVR.WPF.Framework.View.Controls.InputPicker' does not have a resource identified by the URI '/CleVR.WPF.Framework;component/view/controls/inputpicker.xaml'.*

Also the designer does not depict the UserControl but says:
*Cannot create an instance of "InputPicker".*

*Note that this issue only occurs in the designer and not when running*

The issue will persist even when all xaml lines of the WPFLocalizeExtension are disabled (and a clean/rebuild is done). The only way to get the designer working again is to remove both the *bin* and *obj* folder (after the WPFLocalizeExtension xaml lines were disabled) and then rebuild it.

The following code is used:
```
<Window x:Class="Custom.Test.View.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:lex="http://wpflocalizeextension.codeplex.com"
        lex:LocalizeDictionary.DesignCulture="nl"
        xmlns:c="clr-namespace:Custom.WPF.Framework.View.Controls;assembly=Custom.WPF.Framework"
        Title="Test" Height="768" Width="1024"
        xml:lang="en-US">
    <StackPanel>
        <c:InputPicker Style="{StaticResource DSInputPicker}"
                       DataContext="{Binding InputPicker}" />
        <TextBlock Style="{StaticResource DSTextBlock}"
                   Text="{lex:LocText Test:Strings:Test}" />
    </StackPanel>
</Window>
```

Do you have any clue of what may be causing the issue and how we could possibly solve it?
Thanks in advance!

**Comment by MrCircuit** [comment]
Hi,
Sorry, I have no clue. Did you try using the latest revision of our library from source? If not, please stand by - I'm building the next revision right now.
If the problem is not solved with this, please provide a simple example that we can debug.

**Comment by Joris8** [comment]
Thanks for your (really fast :)) reply, I have used the Nuget Package. Currently I am working on a simplified version. I will also try the version built from source. I will let you know about the outcome.

**Comment by Joris8** [comment]
Hi,
I have now made a small project that is having the same issues. Though it was hard to reproduce, but when it is reproduced it continues to exist. Als now the local UserControl is not working instead of the external DLL UserControl. 
How can I send the project files to you?

In the example project I used the manually build master branch version.

The following steps should reproduce the issue in the example project:
 1. Start the project in visual studio (Notice that the LocalizeDictionary.DesignCulture is not working at startup)
 2. Rebuild the solution (Now LocalizeDictionary.DesignCulture is working)
 3. Hit F5 (Start debugging)
 4. Close the application using the cross.
 5. The error occurs as described in the post above.

**Comment by MrCircuit** [comment]
Good question :-)
GitHub apparently does not include a user-to-user communication.

You could fork the project and add your example project as a test.

**Comment by Joris8** [comment]
I made a wetransfer link:
https://www.wetransfer.com/downloads/71ba785775e3fded07d4954e95a00ae520150224112032/ff6fdbba35bfe2ae033d2a81d947e8b220150224112032/e4a6a8

**Comment by MrCircuit** [comment]
OK. Got the file. I'll have a look on it.

**Comment by Joris8** [comment]
Hi,
Have you got the reproduction of the issue working with the example project I have send you?

In the mean time I have tried to find more information about what may be causing the issue.
I have looked into pack URI's (https://msdn.microsoft.com/en-us/library/aa970069(v=vs.110).aspx), and adjusted the line in *App.xaml* to `<ResourceDictionary Source="pack://application:,,,/Style;component/Default.xaml" />`
Unfortunately this did not help, but did make reproduction of the issue a bit harder in some solutions.

Also I figured out that the DesignCulture property is not always working directly (sometimes it starts working after some clean and rebuild steps). Is this a known issue?

I tried to find in the source code the part responsible for the change in culture between editor and execution mode. And if I am correct this is done in `LocalizeDictionary.SetCultureFromDependencyProperty`. Though I could not yet find a piece of code that could cause this problem. Can you pinpoint to me where in the Code the language resource dictionary is searched and loaded? Maybe that is the part that is causing some of the issues?

When I can further assist in looking into certain parts of the code or perform certain tests that help solving this Issue, then let me know.

**Comment by MrCircuit** [comment]
Sorry, I was too busy the last 2 days.
Before, I was once able to reproduce the issue but it didn't show up again after rebuilding the whole solution. Unfortunately, I did not have time then to investigate more on that topic.

Thanks for sharing your ideas. The design culture feature is really an annoying thing, because the designer changed completely since VS2012. The workarounds we found to keep it running have side effects, like the need for a clean/rebuild. For more information, please refer to the older issues of this project. Maybe you come up with a smarter way to solve it.

The resouce dictionary is loaded the first time a localization extension in your code (e.g. the first created element in your first loaded XAML) is looking for a translated resource.

Regarding your other question (LocalizeDictionary.SetCultureFromDependencyProperty) I have to look in the code (it's been a long time...) later.

**Comment by Joris8** [comment]
No sweat, thanks for looking into it.

I also figured out reproduction of the issue is sometimes hard, though sometimes (after reboot of my pc or restart of visual studio) it continues to consist.

At this moment I am  looking into creating Custom Controls instead of using UserControls (With DynamicResource binding) for my own created controls. Maybe this is an underlying issue, but still don't know why the WPFLocalizationExtension triggers the issue and why it does not occur without using the library. So maybe this ain't the issue at all, but at least worth a try.

Sounds frustrating that they changed the designer in VS2012. I will have a look at this issue later on.

I will keep you posted on if creating custom controls solve the issue. In the mean time I am happy to hear from you if you find anything interesting.

**Comment by Joris8** [comment]
It has been a while, but in the meantime I have tested removing DynamicResource, and this seems to make it more stable. Sometimes it still occurs and then a restart of VS2012 is required for the UserControls to be depicted.
So I think DynamicResources need to be avoided and custom controls is the way to go.

Unfortunately I can't seem to figure out what exactly is the problem because it is not really reproducible. Maybe it is something with the caching mechanism of Visual Studio?
