### ISSUE TITLE
Memory leak when using collapsed control within a control template

### ISSUE THREAD

**Issue by roadz99** [SeriousM/WPFLocalizationExtension#52]
Use the localization extension in a control within a collapsed container within a control template. When the Window is closed the localised item is held in memory.

**Comment by SeriousM** [comment]
Is that the issue to the PR #53?

**Comment by roadz99** [comment]
Yes

**Comment by SeriousM** [comment]
The PR #53 is representing the issue already, closing this issue here to reduce irritation.
