### ISSUE TITLE
Ignore casing for keys

### ISSUE THREAD

**Issue by Phyxion** [SeriousM/WPFLocalizationExtension#54]
Is this possible? I already looked a bit through the available properties and did not see this. Did I miss it or does this not exists?

**Comment by SeriousM** [comment]
hmmm, I never faced the problem that a key-case was treated sensitive!
are you sure?

**Comment by Phyxion** [comment]
Yes, I'm 100% sure. Add a language key like: "TestTest" and request "Testtest", it won't return anything.

**Comment by SeriousM** [comment]
My best guess is [this line](https://github.com/SeriousM/WPFLocalizationExtension/blob/master/WPFLocalizeExtension/Providers/ResxLocalizationProviderBase.cs#L708) where the ResourceManager is called.

There is a [IgnoreCase](https://msdn.microsoft.com/en-us/library/system.resources.resourcemanager.ignorecase(v=vs.110).aspx) property on the resource manager which is default to `true`... I don't think we have set this somewhere to `false`?

Could you verify that please?

**Comment by SeriousM** [comment]
oh oh, I've fonud a problem on the msdn documentation about IgnoreCase:

>If the value of the IgnoreCase property is false, a resource with the name "Resource" is not equivalent to the resource with the name "resource". If IgnoreCase is true, a resource with the name "Resource" is equivalent to the resource with the name "resource". **Note, however, that when IgnoreCase is true, the ResourceManager.GetString and ResourceManager.GetObject methods perform case-insensitive string comparisons by using the invariant culture.** The advantage is that results of case-insensitive string comparisons performed by these methods are the same on all computers regardless of culture. **The disadvantage is that the results are not consistent with the casing rules of all cultures.**

Are the keys insensitive when you specify a culture?

**Comment by Phyxion** [comment]
I already specify a culture, it doesn't help. Are you sure IgnoreCase is actually set to true by default? Because it doesn't says so anywhere.

**Comment by Phyxion** [comment]
Just checked it myself, IgnoreCase defaults to false.

**Comment by SeriousM** [comment]
@MrCircuit, are you agree that we just set the property to true on startup, regardless what the user might have set?

**Comment by MrCircuit** [comment]
So you would prefer that we add a controlling property for case sensitivity?
If we don't want to break with the previous behaviour, we should not set it to True by default.

**Comment by Phyxion** [comment]
I would prefer that. It shouldn't break previous behaviour as all it does is allow Testtest to work for TestTest (which you cannot add again in the designer as it says the key already exists).

**Comment by SeriousM** [comment]
Ok, that sounds good. Do we have a entrypoint for initial configuration?
If not, what about the app.config?

**Comment by Phyxion** [comment]
This can be added to Resx..Provider(Base) or just to the Localize...Instance (I do not recall the exact names) as its more of a global setting. Or just set it as default. 

How do you guys feel about opening up ResourceManagerList (see my above post)?

**Comment by SeriousM** [comment]
The ResourceManagerList can be opened as ReadOnlyCollection so we can be still sure that we don't lose any instances and the consumer can modify the instances.

A setting to the Localize...Instance is maybe already too late - depends when the consumer access it the first time. (not all users of the library have a program.cs that startsup the application)

**Comment by Phyxion** [comment]
The ResourceManagerList is a protected property, so I have to use reflector to get it. I'd be nice if you could make this public so it's easier to retrieve this. I'm currently manually setting the ResourceManager in this list so I can use the CreateFileBasedResourceManager method of the ResourceManager to automatically pick all language files from a specific directory as the current resx provider requires you to have all language files in the project.

**Comment by SeriousM** [comment]
Would be a method to get all the resource managers sufficient for you?

**Comment by Phyxion** [comment]
As long as I can modify that collection (and it'll be used :)), sure.

**Comment by SeriousM** [comment]
The collection or the instances?
Am 30.04.2015 13:34 schrieb "Phyxion" <notifications@github.com>:

**Comment by Phyxion** [comment]
Well, I need to be able to add a new resource manager myself (and also be able to call ReleaseAllResources on it), so I'd say both.

**Comment by kim07** [comment]
:+1:
