### ISSUE TITLE
Errors when using WPFLocalizationExtension for Templates or DataContext

### ISSUE THREAD

**Issue by lkettenb** [SeriousM/WPFLocalizationExtension#55]
Hello,

when I use the WPFLocalizationExtension for Templates or DataContext it works as expected, but Visual Studio 2012 produces the following error messages:

For ContextMenu:

    System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContextMenu' (Name=''); target property is 'Parent' (type 'DependencyObject')

For Templates (where a StackPanel is used inside of the template):

    System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'StackPanel' (Name=''); target property is 'Parent' (type 'DependencyObject')

I use the "Assembly:Dictionary:Key" notation as proposed in #31.

Please let me know if you need further information.

**Comment by SeriousM** [comment]
hmmm, I guess @MrCircuit is the right person for such a problem. I
hadn't my hands in the RelativeSource since years :(

**Comment by MrCircuit** [comment]
I also seldomly had this issue, where this binding to the Parent property failed. But I did not find a solution to it. On the other hand, it never lead to a failing translation...

IMHO it's a Mandelbug :-).

**Comment by ChristianPerner** [comment]
I had the same issue. After adding 
```XML
lex:ResxLocalizationProvider.DefaultDictionary="Resources"
```
to the view it doesn't show up again.
The "Assembly:Dictionary:Key" notation doesn't fix the problem.
hth

**Comment by alanwol** [comment]
I have both:

lex:ResxLocalizationProvider.DefaultDictionary="Resources"

and "Assembly:Dictionary:Key" notation but still have this problem.

I get it when I use a context menu inside a DataTemplate

 <ContextMenu>
        <MenuItem Header="{lex:Loc MyAssembly:Resources:Header_TEXT}" />
 </ContextMenu>

**Comment by SeriousM** [comment]
Could you assemble a small test program so that we can investigate it?

**Comment by SeriousM** [comment]
Closed due lost contact

**Comment by alanwol** [comment]
Hi Bernhard,

What does it mean closed due to lost contact?

Regards,
Alan
Op 17 nov. 2015 9:52 PM schreef "Bernhard Millauer" <
notifications@github.com>:

**Comment by SeriousM** [comment]
Hi Alan!
Well, I asked for a small test application but nothing happend after that, so I guess you lost interest solving the problem. 
If that's not the case, please feel free to open the issue again. 
Thank you :)
