### ISSUE TITLE
Localized text is only displayed first time in design mode

### ISSUE THREAD

**Issue by mgnslndh** [SeriousM/WPFLocalizationExtension#59]
Hi,

I am experiencing a problem with localized text in design time. The first time I open a view the localized text is displayed according to the DesignCulture specified in the XAML. If I close and reopen the view the text displayed will be "Key: Description" or something similar depending on the actual key in use. I guess I must have missed some step in setting up the view but I have tried to follow the available documentation. Everything works great in runtime and the _first_ time I open the view in design time.

The only modifications I have done to the view is to add XAML namespace and the required settings:

             xmlns:l="http://wpflocalizeextension.codeplex.com"
             l:LocalizeDictionary.DesignCulture="en-US"    
             l:ResxLocalizationProvider.DefaultAssembly="Some.Assembly"
             l:ResxLocalizationProvider.DefaultDictionary="Modules.ErrorList.Resources.Translations"

The text is a simple binding like this:

                    <telerik:GridViewColumn Width="*" Header="{l:Loc Description}" HeaderCellStyle="{StaticResource DefaultHeaderCellStyle}"/>

Any ideas?

I am using WpfLocalizationExtension v2.3

**Comment by Acaspita** [comment]
I found that in MemoryTest sample project, if you exclude the Resources.resx file side with its designer file, you'll get the "Key: KeyValue" text, despite changing the localization at MainWindow.xaml.cs to "de"...
This makes me think that the resouces files need a main resources file that only has the keys, and then the individual resx files for every localization you need to implement, to avoid this issue.
Please mark it as solved if it fixed it.
Regards,

**Comment by MrCircuit** [comment]
But this comes to the cost of loosing the invariant culture fallback.
Nevertheless, I still don't exactly understand the issue and the solution...
