### ISSUE TITLE
Binding on code behind.

### ISSUE THREAD

**Issue by ckocer** [SeriousM/WPFLocalizationExtension#60]
Hi there.
I couldn't find any document about binding on code behind.
I've a few MessageBoxes and I don't know how to bind strings to these MessageBoxes.

Can you help me. Thank you!

**Comment by SeriousM** [comment]
Hi ckocer,

you're right, we don't have any test code (anymore).
Anyway, here is the API for it:
https://github.com/SeriousM/WPFLocalizationExtension/blob/master/WPFLocalizeExtension/Extensions/LocExtension.cs#L768

It works for DependencyObjects as well as normal Objects.
The property may be a DependencyProperty as well as a normal Property.

If you have any questions don't hesitate to ask.

Cheers, Bernhard

**Comment by ckocer** [comment]
Hi, thank you for fastest answer.
But my English is not that good. The "Binding" word is actually wrong for my question.

How can I get the localized texts using Keys to use MessageBox like this.
MessageBox.Show( .... localized text will be here ... );

**Comment by SeriousM** [comment]
Thats even easier!
Either with [GetLocalizedValue](https://github.com/SeriousM/WPFLocalizationExtension/blob/master/WPFLocalizeExtension/Extensions/LocExtension.cs#L588) (Static method) or with [ResolveLocalizedValue](https://github.com/SeriousM/WPFLocalizationExtension/blob/master/WPFLocalizeExtension/Extensions/LocExtension.cs#L684) (Instance method).

Just pick the right overload of the methods.
