### ISSUE TITLE
Memory leak when localizing a ContextMenu

### ISSUE THREAD

**Issue by ctusch** [SeriousM/WPFLocalizationExtension#62]
Hey,

when I localize a MenuItem's Header property within a ContextMenu your library keeps the reference to that MenuItem even after removing the containing control from the UI.

Here you can see the relevant root path:
![image](https://cloud.githubusercontent.com/assets/6949649/8256873/2777ed62-16aa-11e5-8bbd-37fadb36be3b.png)

Here you can download my sample project:
https://drive.google.com/uc?export=download&id=0B8jB0VV77K21ZzFyODJ6OGtscm8&authuser=0

**Comment by SeriousM** [comment]
Hi @ctusch, I'll have a look at it.
Thanks for reporting!

**Comment by SeriousM** [comment]
Found the issues which spans over XAMLMarkupExtensions and WPFLocalizationExtension.
How important is the fix for you @ctusch?

**Comment by SeriousM** [comment]
Alright @ctusch, @MrCircuit is fixing the leak on the XAMLMarkupExtensions side, I already fixed it on WPFLocalizationExtension. Just hang on until the new packages are created and published.

**Comment by kroimon** [comment]
It would be great if you could also fix #52 / #53 for this release as it leaks memory when translating collapsed elements.

**Comment by ctusch** [comment]
Great @SeriousM, thanks for the fast response! Will test it when it's released.

**Comment by SeriousM** [comment]
> It would be great if you could also fix #52 / #53 for this release as it leaks memory when translating collapsed elements.

@MrCircuit is currently adding your changes in LocExtension.cs to the upcoming release.

**Comment by ctusch** [comment]
Hey @SeriousM, sorry I've been sick the past two days. I've tested your fix today. It fixes the problem in my sample application but the solution causes an null reference exception in our real application. Wasn't able to figure out the reason. A simple null check should do but maybe there is a bigger underlying problem.

![image](https://cloud.githubusercontent.com/assets/6949649/8380190/bf58c21c-1c24-11e5-825e-27f884454590.png)

**Comment by MrCircuit** [comment]
refs #64
