### ISSUE TITLE
ParentChangedNotifier Target null causing crash

### ISSUE THREAD

**Issue by steveadoo32** [SeriousM/WPFLocalizationExtension#64]
Hi,

I'm using MvvmCross for my application, and it involves a presenter to show your Views. My presenter is just a Window and I replace the Windows content with the view when navigating. I noticed that if I switch views, my app will crash at ParentNotifiers's Remove method, specifically:

        _inner[singleOrDefault].Target.Dispose();

Honestly, I'm not sure if this is because I'm using MvvmCross or I'm doing something wrong, just wanted to give you guys some context.
I can just add a check to make sure Target isn't null before disposing it and it will work, but is this going to cause any memory leaks or issues?

**Comment by MrCircuit** [comment]
I fixed it the way you propose, because when the Target is null (or not alive) it's safe to not call Dispose.

**Comment by SeriousM** [comment]
Please read the comment on [c72a992](https://github.com/SeriousM/WPFLocalizationExtension/commit/c72a992f295d01d0097e1cfa7deace71a3866ca7#commitcomment-11901110)
