### ISSUE TITLE
Binding with string.Format

### ISSUE THREAD

**Issue by ckocer** [SeriousM/WPFLocalizationExtension#65]
Hi, is there any way that I can bind formatted texts to (for example) MenuItem.HeaderProperty ?

Sample localized text: You have reached level {0} of {1}.

**Comment by MrCircuit** [comment]
There is a specific LocTextExtension for this purpose. Otherwise, use a proxy class similar to the LocProxy class.

**Comment by tempywritescode** [comment]
@MrCircuit Could you possibly elaborate on using LocTextExtension for this? I basically tried what [this person on SO](http://stackoverflow.com/questions/9520030/markupextension-converting-a-simple-property-to-dependencyproperty) tried and got the same result as him. I want to make sure I'm not missing anything obvious before I start trying to roll something of my own.

**Comment by MrCircuit** [comment]
refs #78
