### ISSUE TITLE
How to switch language to display?

### ISSUE THREAD

**Issue by OfekA** [SeriousM/WPFLocalizationExtension#66]
I looked at the documentation and I couldn't find a way to change the user language, any help?

**Comment by UeliHilfiker** [comment]
I hasn't found it too, but you can change the language on this way:

Source in vb.net:
```vb.net
WPFLocalizeExtension.Engine.LocalizeDictionary.Instance.Culture = System.Globalization.CultureInfo.CreateSpecificCulture("de")
```

**Comment by UeliHilfiker** [comment]
or for C#
look at this Example Code:
https://github.com/SeriousM/WPFLocalizationExtension/blob/master/Tests/LocalizationTest/App.xaml.cs

You can find example sources (C#, VB, SL, Phone, etc.) in Tests - folder:
https://github.com/SeriousM/WPFLocalizationExtension/tree/master/Tests

**Comment by OfekA** [comment]
Thanks a lot, I didn't know about the examples in the Tests directory.

I will try what you suggested, thanks.

**Comment by OfekA** [comment]
Your first example worked perfectly, thanks a lot!
