### ISSUE TITLE
How to localize Text on an element inside of a ResourceDictionary ?

### ISSUE THREAD

**Issue by JamesWHurst** [SeriousM/WPFLocalizationExtension#67]
This seems to work just fine for localizing text within normal XAML views. But what about within a XAML ResourceDictionary?
For example, within Themes\Generic.xaml  I define this..

```
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
     ...
                    xmlns:lex="http://WPFLocalizationExtension.DesignForge.com">
    <Style TargetType="layoutToolkit:AccordionItem">
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="layoutToolkit:AccordionItem">
     <Style TargetType="layoutToolkit:AccordionItem">
                       <Border x:Name="Background" 
                                            <TextBlock Text="{lex:Loc Step}"/>
```
This resource-key, "Step", fails to be translated. Also, if I put lex:ResxLocalizationProvider.DefaultAssembly=".." or .DefaultDictionary="..", the compiler complains about those.

Does WPFLocalizationExtension not work within XAML ResourceDictionaries ?

**Comment by MrCircuit** [comment]
It is working. I tested this one right now to double-check:
```XAML
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:sys="clr-namespace:System;assembly=mscorlib"
                    xmlns:l="http://wpflocalizeextension.codeplex.com">
    <DataTemplate DataType="{x:Type sys:Enum}">
        <Grid>
            <TextBlock Text="{Binding ElementName=Proxy, Path=Result}" />
            <l:LocProxy Name="Proxy" Source="{Binding}" PrependType="True" />
        </Grid>
    </DataTemplate>
</ResourceDictionary>
```
What you cannot do there is setting any attached properties to the ResourceDictionary (DefaultAssembly & DefaultDictionary). But their values will be taken from the target where the templates will be used.

**Comment by arteny** [comment]
It is not working when I set this properties in element where this datatemplated object is used as content.
Textblock form example return nothing for me.
