### ISSUE TITLE
Binding on code behind is too slow :(

### ISSUE THREAD

**Issue by ckocer** [SeriousM/WPFLocalizationExtension#68]
Hi there,
I'm using your library for my app and i realized that the binding is too slow and slows down evertthing.

I've written a static class named "L.cs" to use your class easier.
public static void Bind(DependencyObject dObj, DependencyProperty dProp, string key)
{
	new LocExtension(key).SetBinding(dObj, dProp);
}

this is my static class to bind ListViewItem's Header property. Using it like:
L.Bind(myListViewItem, ListViewItem.ContentProperty, "someKey");

And I have a list that contains 50 - 60 (max) items in it. Creating that list with binding takes 2 seconds.

This is the method that i use to fill my list.
private void FillList()
{
	for (int i = 0; i < _lastSelections.Count; i++)
	{
		var lwi = new ListViewItem();
		L.Bind(lwi, ListViewItem.ContentProperty, "key1");
		lwi.Tag = _lastSelections[i];

		myOwnList.Items.Add(lwi);
	}
}

I really need your help to fix it.
Thank you @MrCircuit and @SeriousM  !

**Comment by MrCircuit** [comment]
Hi @ckocer,

I also used larger lists including localized entries without any problem, but using XAML techniques. Can you extract an example project illustrating this problem and send it to us? This would help finding the issue.

**Comment by SeriousM** [comment]
Closed due lost contact
