### ISSUE TITLE
Multiple resource assemblies not working/false documented

### ISSUE THREAD

**Issue by indazoo** [SeriousM/WPFLocalizationExtension#69]
Hi
I just started to use this extension really the basic steps.
Then I wanted in my simple view use resources from two different assemblies and read the doc here:
https://wpflocalizeextension.codeplex.com/wikipage?title=Multiple%20assemblies%20and%20dictionaries

But the "Assembly" property and "Dict" property no longer exist. I found them in source (June 2012) with depreceated flag:
https://github.com/SeriousM/WPFLocalizationExtension/blob/6d92b800c9867d36caa476cc9c33203763eae6b5/WPFLocalizeExtension/Extensions/LocExtension.cs

 [Obsolete("This property is obsolete and will be removed from the extension in the future.\r\nUse the attached properties of the ResxLocalizationProvider instead.")]
        public string Assembly
        {
            get { return this.assembly; }
            set { this.assembly = !string.IsNullOrEmpty(value) ? value : null; }
        }
So the syntax <Button Content="{lex:Loc Test, Assembly=MyAssembly, Dict=MyResource}" />
no longer works. In code the current version of LocExtension do not have the properties.

What is the new way to do it?
Could you please give me a pro tip and/or update the doc?

**Comment by indazoo** [comment]
Oh, Now I see the full text. In Github I only saw this:
"This property is obsolete and will be removed from the extension in the future.\r\nUse the attached properties"  without " of the ResxLocalizationProvider instead." at the end because the GitHub Gui makes no "autoWrap" (which may be good).

This means I can only change resources per Control? Hmm..

**Comment by indazoo** [comment]
This works, is this the correct (only)way now? 
<StackPanel lex:ResxLocalizationProvider.DefaultAssembly="My.Other:Assembly">
        <TextBlock Text="{lex:Loc Key=OS}" Grid.Row="0" Grid.Column="0" ></TextBlock>
    </StackPanel >

**Comment by indazoo** [comment]
Don't bother, I'll not use it. 
I missed too much the intellisense for my resource keys.

**Comment by MrCircuit** [comment]
Sorry for the late answer, but you're right. There are two ways:
* Use the attached properties
* Use the extended key syntax (`MyAssembly:MyResource:Test`).
