### ISSUE TITLE
Why is enum localization so counter-intuitive?

### ISSUE THREAD

**Issue by nzain** [SeriousM/WPFLocalizationExtension#70]
I was using your project for a while now, using a custom provider, very nice. However, today I tried to localize an enum value. Following the documentation at 

  https://wpflocalizeextension.codeplex.com/wikipage?title=LocProxy%20%26%20EnumComboBox&referringTitle=Documentation

I first have to add an FrameworkElement with zero size only to bind to some obscure Result property? 

<lex:LocProxy Source="{Binding}" x:Name="Proxy" PrependType="True" />
<TextBlock Text="{Binding Result, ElementName=Proxy}" Margin="2" FontWeight="Normal" />

Why not extend on Run, which could be used inside a TextBlock?
Plus, I have no control over the key: I'd like to specify a prefix different from the enum name.

Eventually, I find the time to write such a markupextension using your framework and post back here asap.

**Comment by SeriousM** [comment]
Hi @nzain,

> Eventually, I find the time to write such a markupextension using your framework and post back here asap.

That would be great!!

**Comment by nzain** [comment]
Ok, so my quick fix was to use a converter. This might not work for everyone, since you don't have the DependencyObject in the Convert method and it depends on static access to the LocalizeDictionary.Instance singleton. However, the usage does not require declaration of ghost-UiElements, is more intuitive, and allows me to speficy a custom prefix (via `ConverterParameter`) instead of the enum's type name.

    <Some.Resources>
        <conv:EnumLocalizer x:Key="EnumLocalizer" Separator="." />
    </Some.Resources>
    ...
    <TextBlock Text="{Binding Track.TrackSource, 
        Converter={StaticResource EnumLocalizer},
        ConverterParameter=MyFriendlyPrefix}" />

A MarkupExtension would fit much better into your framework, but I don't have the time / deeper understanding of your framework to work out the details. For those interested, here is the really simple code:

    /// <summary>Converts enum values into localized texts.</summary>
    /// <remarks>Suppose you have an <c>enum Side</c> with two values <c>Side.Left</c> and <c>Side.Right</c>. In your XAML you
    /// want to bind to a viewmodel with that enum, but the user wants to see localized text. First, define a static resource
    /// somewhere, e.g. in <c>app.xaml</c> or at element level.
    /// <code>
    /// &lt;Xyz.Resources&gt;
    ///     &lt;conv:EnumLocalizer x:Key="EnumLocalizer" /&gt;
    /// &lt;/Xyz.Resources&gt;
    /// </code>
    /// When binding some text element to your view model's enum property
    /// <code>
    /// &lt;TextBlock Text="{Binding TheEnumSideProperty, Converter={StaticResource EnumLocConv}}" /&gt;
    /// </code>
    /// the <c>LocalizeDictionary</c> is querried for the key <c>Side/Left</c> (or Right respectively). Optionally, you can
    /// specify the <c>Separator</c> (defaults to slash) and the prefix if you don't want to see the enum's type name. The
    /// prefix is given as the <c>ConverterParameter</c> at runtime.
    /// <code>
    /// &lt;TextBlock Text="{Binding TheEnumSideProperty, Converter={StaticResource EnumLocConv}, ConverterParam=SomeSpecialPrefix}" /&gt;
    /// </code>
    /// </remarks>
    [ValueConversion(typeof(Enum), typeof(object))]
    public class EnumLocalizer : IValueConverter
    {
        private string _separator = "/";

        /// <summary>Gets or sets the Separator between the enum class or converter parameter and the enum value.</summary>
        public string Separator
        {
            get { return this._separator; }
            set { this._separator = value ?? string.Empty; }
        }

        /// <summary>Converts the given enum value into a localized object.</summary>
        /// <param name="value">The enum value (binding source).</param>
        /// <param name="targetType">Not used.</param>
        /// <param name="parameter">The converter parameter (if not <c>null</c>) replaces the enum's type name as a prefix.</param>
        /// <param name="culture">The culture used for localization.</param>
        /// <returns></returns>
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var dic = LocalizeDictionary.Instance;
            if (dic == null || value == null)
            {
                return value;
            }
            string prefix = parameter != null
                ? parameter.ToString() // use the parameter as prefix, if given
                : value.GetType().Name; // otherwise fallback to enum's type name

            string key = prefix + this.Separator + value;
            object localized = dic.GetLocalizedObject(key, null, culture);
            return localized ?? "Key: " + key;
        }

        /// <summary>Not supported.</summary>
        /// <param name="value">Not supported.</param>
        /// <param name="targetType">Not supported.</param>
        /// <param name="parameter">Not supported.</param>
        /// <param name="culture">Not supported.</param>
        /// <returns>Trouble.</returns>
        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotSupportedException();
        }

**Comment by MrCircuit** [comment]
Hi @nzain,

Let me first start with the description of the problem why the current solution is as it is:
The most common situation is that one may want to bind a localized enum property to a visual, like a TextBox, a ComboBox etc. This means, that we need a Binding and we need some way to inject the localization. There are two major restrictions to that: A Binding instance must not change after beeing created (it is freezed). A Binding MarkupExtension cannot be applied to a non-DependencyProperty and therefore not to another MarkupExtension such as ours.

Your approach is one possible way and also one of the simple ways to offer localization in general. Unfortunately, this approach will not switch language, respond to dictionary changes etc. at runtime because the converter is only called when the Binding source (thus, the enum value) changes. If this is sufficient for your needs - go for it.

Another approach is our solution: Create a helper DependencyObject that serves as the enum Binding target and that creates a second "living" bond of our localization engine another property such as "Result" that can be used in another Binding again. The enum value itself serves as the key to the localization engine. You mentioned drawbacks: You want a custom prefix string? Just ask :-). The hidden LocProxys are bloating your XAML code? Partially true, but for this issue, I have the following suggestion: Use a template in the resources to describe enum localization in general. The most general approach would be to template the System.Enum type (or particular ones as you prefer) itself in your window root resources:
```XAML
<DataTemplate DataType="{x:Type sys:Enum}">
  <Grid>
    <TextBlock Text="{Binding ElementName=Proxy, Path=Result}" />
    <l:LocProxy Name="Proxy" Source="{Binding}" PrependType="True" />
  </Grid>
</DataTemplate>
```
Last but not least one may also think of a similar approach, but combined with the markup extension itself. This calls for an internal Binding handling (including all aspects such as memory safety) to be able to retrieve the enum value. Given this, the output target(s) can then be updated at language, dictionary or when the Binding values changes.

**Comment by nzain** [comment]
Ah, well. I knew, my approach is very simplified - but I really forgot about the dynamic culture change, which is a required feature for me. So my approach is crap, agree.

Admittedly, I don't really understand the MarkupExtension/Binding details, I thought one could create a DependencyProperty inside the MarkupExtension, much like you do with attached properties when you define them in a static class which is not a DependencyObject itself. Probably wrong, because there is no other DependencyObject to attach to, ha.

Ok, brain reset. The most common scenario for localized resources is text (the only relevant for me), but I can understand that someone might localize images. Would it be feasible / possible to extend the class Run, which can be used inside TextBlocks? This would simplify the most common (am I wrong?) Scenario. Something like

    <TextBlock>
        <Run Text={lex:LocText someRegularTextKey} />
        <lex:EnumRun EnumValue="{Binding MyEnumProperty}" Prefix="OverrideEnumTypeNameHere" Separator="." />
    </TextBlock>

such that the LocalizeDictionary is querried for `OverrideEnumTypeNameHere.SomeEnumValue`.

Your template idea looks good as well, although I didn't know that I can template non-UI-elements. However, I could not specify a prefix here, when defining this template globally. Background on my prefix issue: Some of our customers translate the applications into their own language. Thus, the keys have to be comprehensible for a non-programmer. The enum's type name, however, usually reflects the programmers view!

  *You want a custom prefix string? Just ask :-)*
Sorry for not doing so. Actually, I had some very rude experiences with open source developers.

best, nZain

**Comment by nzain** [comment]
Actually, the prefix could be completely separated (optional, defaults to null) plus a bool PrependTypename like you use for the LocProxy. This way one could build more complex keys like
`MyCustomPrefix.EnumTypeName.EnumValue`.

**Comment by MrCircuit** [comment]
Hi,

Yes, you can create data templates for non-WPF elements - it's just a dictionary with the data type as the key and a visual representation as the value (IMHO one of the most important features of WPF for MVVM pattern support). Therefore you can template each particular enum type in your solution in a different way with its own prefix.

Nevertheless I will try to have a look on the proposed extension of Run.
Additionally, I will add your proposed custom prefix feature (we try not to be rude :-)).

**Comment by nzain** [comment]
Obviously, viewmodels are never UI elements and you template them every day. I just never thought about this for an enum (which does not implement INotifyPropertyChanged etc.).

Thanks for looking into this! I'm looking forward to an update :-) :+1:

**Comment by GeroIwan** [comment]
Maybe the following approach works for you. It uses an encapsulated MultiBinding in order to update the binding if the localization culture changes. The MultiValueConverter is written on the lines of the ValueConverter given above. The C# code is:
```C#
    using System;
    using System.Globalization;
    using System.Windows;
    using System.Windows.Data;
    using WPFLocalizeExtension.Engine;

    public class EnumBinding : MultiBinding
    {
        private static readonly EnumLocalizer _defaultEnumLocalizer = new EnumLocalizer();
        private static readonly Binding _cultureBinding = new Binding("Culture") {
            Source = LocalizeDictionary.Instance, Mode = BindingMode.OneWay };
        private Binding _pathBinding = null;
        private String _path = null;

        public String Path
        {
            get
            {
                return _path;
            }
            set
            {
                if ( _path != value )
                {
                    _path = value;

                    _pathBinding = new Binding(_path) {
                        UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged, ... };
                    Bindings.Clear();
                    Bindings.Add(_pathBinding);
                    Bindings.Add(_cultureBinding);
                }
            }
        }

        public EnumBinding()
        {
            Converter = _defaultEnumLocalizer;
        }

        public EnumBinding(String path) : this()
        {
            Path = path;
        }
    }

    public class EnumLocalizer : IMultiValueConverter
    {
        private const String _defaultSeparator = ".";

        public String Separator
        {
            get;
            set;
        }

        public Object Convert(Object[] values, Type targetType, Object parameter, CultureInfo culture)
        {
            var enumerator = values[0];
            if ( enumerator == null || enumerator == DependencyProperty.UnsetValue || LocalizeDictionary.Instance == null )
            {
                return enumerator;
            }
            else
            {
                var prefix = (parameter != null ? parameter.ToString() : enumerator.GetType().Name);
                var key = prefix + (Separator ?? _defaultSeparator) + enumerator;
                var localized = LocalizeDictionary.Instance.GetLocalizedObject(key, null, LocalizeDictionary.Instance.Culture);
                return (localized ?? "Key: " + key);
            }
        }

        public Object[] ConvertBack(Object value, Type[] targetTypes, Object parameter, CultureInfo culture)
        {
            throw new NotSupportedException();
        }
    }
```
The usage in XAML is very similar to the above converter-only approach:
```XAML
    <Some.Resources>
        <xyz:EnumLocalizer x:Key="EnumLocalizer" Separator="." />
    </Some.Resources>
...
    <TextBlock Text="{xyz:EnumBinding Path=Track.TrackSource, Converter={StaticResource EnumLocalizer}, ConverterParameter=MyFriendlyPrefix}" />
```
Note that `Path=` can be omitted (although I prefer to not omit it) and that no converter has to be specified when the default separator is okay. Then the XAML simplifies to:
```XAML
    <TextBlock Text="{xyz:EnumBinding Track.TrackSource, ConverterParameter=MyFriendlyPrefix}" />
```

**Comment by MrCircuit** [comment]
Hi @GeroIwan,

thanks for your suggestion. Unfortunately, this approach suffers from having no access to the dictionary and assembly settings of the resource provider. This issue goes deeper into the mechanics of the MarkupExtension base class and the - unfortunately - poor access to the necessary information of the extension target in the Binding and MultiBinding classes.

If your resource provider does not need this, than you're all set. Otherwise you need to find another workaround.

**Comment by MrCircuit** [comment]
Hi @nzain,

Your proposed approach by extending Run is ready for testing. My own first tests look good. Custom prefixes are also possible using the Prefix property (also in LocProxy).

**Comment by nzain** [comment]
Thanks a lot, Mr Circuit! I'll look into it right now.

**Comment by nzain** [comment]
Tested, Great: much more intutive + custom prefix (which also allows to override the enum type name).

Given the problems with other approaches, this seems to be the best compromise between fancy functionality (dynamic language change at runtime, binding different dictionaries to different dependency objects etc.) and simple usage like this:

    <TextBlock>
         <Run Text="{lex:LocText Key=Foo.Category, Suffix=:}"/>
         <lex:EnumRun EnumValue="{Binding TheEnum}" Prefix="Foo"/>
    </TextBlock>

When you update the wiki page for enum localization you could link to this issue, so other users that don't like the LocProxy approach understand the problem.
