### ISSUE TITLE
Runtime problem to translate

### ISSUE THREAD

**Issue by LordLaurent** [SeriousM/WPFLocalizationExtension#71]
Hello,
I've started using the WPF Localization Extension to localize my resources for WPF projects. I like the library because it can easily locate resource's out of the XAML-Code.

My project contains some assembly (one by specific view) and I want to use one dictionnary resource by assembly that contain the key specific to the assembly. I have a problem on an assembly where I want to translate a DataGrid.

<DataGrid>
                <DataGrid.Columns>
                    <DataGridTextColumn Header="{lex:Loc Test}"  Width="Auto"/>
                </DataGrid.Columns>
            </DataGrid>

In the usercontrol balise:

         xmlns:lex="http://wpflocalizeextension.codeplex.com"
         lex:ResxLocalizationProvider.DefaultAssembly="MyModules.Test"
         lex:ResxLocalizationProvider.DefaultDictionary="Resources"

The translation work in design time. But at runtime, I have the key:Test at the header text. After I click on one row of the grid, the translation is correctly updated and it work perfectly but I need to click on a row. In other usercontrol of another assembly, I use a simple TextBlock and the translation work fine directly.

In the main assembly, I initialize the application:

        LocalizeDictionary.Instance.SetCurrentThreadCulture = true;
        LocalizeDictionary.Instance.SetCultureCommand.Execute("fr");

What I need to do?

**Comment by MrCircuit** [comment]
Hi @LordLaurent,

What you describe is a deeper problem of WPF: The DataGrid breaks the Parent/Child relationship tree that is needed for Attached Property retrieval. Therefore, the loc extensions inside the DataGrid can't access the DefaultAssembly and DefaultDictionary values.

Possible workarounds are:
(A) to add these attached properties inside of your DataGrid elements
(B) to use the extended key syntax: Assembly:Dictionary:Key

**Comment by LordLaurent** [comment]
Ok thank you for the answer.
I just tested the option B and it work fine.
I have not understand the possibility A, have you a simple sample ?

**Comment by MrCircuit** [comment]
For example, you could define these attached properties to containers that build up the item cells. This of course might lead to a similar or even higher effort than option B, if each cell needs these attached properties for just one localized value. It therefore depends on the situation.

**Comment by LordLaurent** [comment]
I try now to translate a binding text value. I try with the xamlmarkupextensions like that:
<GroupBox  Header="{ext:DynBinding Path=Title }">
I want to translate the value on Title but only the original value is showed.
What is wrong or what is the possibility?

**Comment by MrCircuit** [comment]
Still an issue? If yes, do you have an example?

**Comment by MrCircuit** [comment]
If it is still an issue, please open a new ticket with an example
