### ISSUE TITLE
LocProxy queries for invalid keys during initialization

### ISSUE THREAD

**Issue by nzain** [SeriousM/WPFLocalizationExtension#72]
When using the LocProxy to localize enum values, the LocalizeDictionary is first queried for `"_Result"` and then for the empty string before the correct key is built. Expected behavior: The dictionary is not queried until the correct key is built.

    <TextBlock Text="{Binding ElementName=Proxy, Path=Result}">
        <lex:LocProxy Name="Proxy" PrependType="True" Separator="/" 
                               Source="{Binding EnumValue}" />
    </TextBlock>

This results in warnings during application startup, since those keys are not found inside a custom provider. I can manually ignore those two strings, but that seems wrong.

best, nZain

**Comment by MrCircuit** [comment]
This issue was solved by moving the construction of the loc extension object to the first place when it's needed and a key is present.
