### ISSUE TITLE
Localizations showing as key: <key> at runtime and designtime

### ISSUE THREAD

**Issue by melance** [SeriousM/WPFLocalizationExtension#75]
I have installed WPFLocalizationExtension using NuGet to my VS2013 .NET 4.5 VB application.  I added the namespace and initialization to my window definition:

```
xmlns:lex="http://wpflocalizeextension.codeplex.com"
lex:ResxLocalizationProvider.DefaultDictionary="Strings"
lex:ResxLocalizationProvider.DefaultAssembly="TheRandomizerWPF"
lex:LocalizeDictionary.DesignCulture="en"
```

I added a resx file named Strings.resx and one named Strings.en-US.resx to my project that use the `PublicResXFileCodeGenerator` custom tool.  I set them to be a public embedded resource and added a key "tools_menu" => "Tools" to both. 

I added a binding to my menu item:

```
<MenuItem x:Name="mnuTools" Header="{lex:Loc Key=tools_menu}">
```

Yet when my menu item now displays "Key: toolsmenu" in both designtime and runtime.

**Comment by NoFear23m** [comment]
I have the same issue as melance.
I am using VisualStudio 2015 with .NET 4.6

**Comment by MrCircuit** [comment]
Have you tried the same key on a simple TextBlock in your window? If it works there, then MenuItem itself or its container - the tool menu - is the problem (refer to various discussions on that topic before). In that case, try to use the full notation at the key, like in your case: "TheRandomizerWPF:Strings:tools_menu". It should work then.

**Comment by NoFear23m** [comment]
Thanks
OK, i have created a new Project and now it works. But in VS 2015 is have not Designtime support. Is it right?

**Comment by MrCircuit** [comment]
I'm working with VS2015 and it works even during design time :-o.

**Comment by melance** [comment]
Sorry it's taken me so long to reply.  I've been very busy with other things.  I tried what you mentioned and created a TextBlock with the following tag:

    <TextBlock Text="{lex:Loc Key=TheRandomizerWPF:Strings:tagslabel}" Foreground="{DynamicResource IdealForegroundColorBrush}" FontWeight="Bold" />

I also tried with {lex:Loc Key=tagslabel} which also didn't work.  Presently the textblock displays Key: TheRandomizerWPF:Strings:tagslable in both runtime and designtime.

Thanks.

**Comment by MrCircuit** [comment]
@SeriousM  If I remember correctly, we once had some issues with VB.NET projects due to their nature of assembly and/or namespace naming. Is this correct and if yes, what was the result?

**Comment by gen3ric** [comment]
I recently ran into this problem. For me, it was because I upgraded from ~2.1.2 to the latest NuGet package and had previously been using the `Loc` markup extension (e.g., `Text="{localize:Loc key.path}"`) but it was fixed when I switched to using `BLoc`. YMMV.

**Comment by jstevenson72** [comment]
I too am having a similar issue.  Although it only seems to fail at Design Time.

![image](https://cloud.githubusercontent.com/assets/1573442/14641798/912fa904-060d-11e6-8174-1147de8f2087.png)

![image](https://cloud.githubusercontent.com/assets/1573442/14641864/cb583ac4-060d-11e6-9764-e02bf9d0c108.png)

I tried switching from Loc to BLoc but it only made the key name disappear at Design Time. Although it continued to work at Runtime.

I installed via the NuGet package into Visual Studio 2015 Update 2.

![image](https://cloud.githubusercontent.com/assets/1573442/14641906/f5dd8b0a-060d-11e6-82b5-5dfc5da9d3dc.png)

![image](https://cloud.githubusercontent.com/assets/1573442/14641918/0128495a-060e-11e6-9216-8dccd5610f72.png)

![image](https://cloud.githubusercontent.com/assets/1573442/14641955/1ff95932-060e-11e6-88cd-f48cac8153b5.png)

**Comment by torpederos** [comment]
Hi, maybe you should try to restart designer. You can configure this process as external tool like this:
![image](https://cloud.githubusercontent.com/assets/4268593/14642213/e919f098-0649-11e6-914d-bcc6e0c1337a.png)

**Comment by jstevenson72** [comment]
That is a great tip, however I have had this problem since yesterday, across multiple reboots, and restarts of VS.

Interestingly the problem partially goes away when using Blend instead of VS Designer.  Some fields are working at DesignTime while others are no longer working.

VS Designer:
![image](https://cloud.githubusercontent.com/assets/1573442/14642757/54c7b0ac-0611-11e6-8e24-55e12359748d.png)

Blend:
![image](https://cloud.githubusercontent.com/assets/1573442/14642785/666fb976-0611-11e6-88c1-1ba608e90926.png)

**Comment by jstevenson72** [comment]
OK.  After killing all XDesProc.exe processes I am now getting a uniform behavior between both Blend and VS Designer.  But there are still a few items that show keys rather than the default translations.

**Comment by rgilmutdinov** [comment]
In my case I fixed the problem by checking "Enable Project Code" option in XAML Designer of VS2015
![image](https://cloud.githubusercontent.com/assets/8816279/22854305/a45c555e-f095-11e6-82e5-278ac294c9cd.png)

**Comment by jstevenson72** [comment]
Yes.  Also if you have any design-time exceptions caused by your ViewModel
it will crash the XDesProc.exe causing it to reload with code disabled.

Thank you.

**Comment by Angelinsky7** [comment]
Got this issue when passing from 2.3.2 to 2.3.4
my `{lex:Loc ch.infodev.srunner.infrastructure:Ressources:Open}"` binding were working but now they don't resolve...

**Comment by SeriousM** [comment]
Closed due stall conversation
