### ISSUE TITLE
Localization with Caliburn Micro

### ISSUE THREAD

**Issue by arcuri** [SeriousM/WPFLocalizationExtension#76]
I'am using Caliburn Micro for developing my multilanguage application. It is compose by the main panel and several modules that are loaded runtime by the bootstrapper and placed in AvalonDock panels. 

The multilanguage works perfectly in the main panel (messages are correctly retrieved based on current culture) while all the modules load correctly only the Resource Manager but are not able to load other cultures. 

Following step by step the code, I realized that in the function 
protected ResourceManager GetResourceManager(string resourceAssembly, string resourceDictionary) in the file "ResxLocalizationProviderBase.cs" the next piece of code is not working:

        try
        {
          var assemblyLocation = Path.GetDirectoryName(assembly.Location);
          
          // Get the list of all cultures.
          var cultures = CultureInfo.GetCultures(CultureTypes.AllCultures);

          foreach (var c in cultures)
          {
            var rs = resManager.GetResourceSet(c, true, false);
            if (rs != null)
              AddCulture(c);
          }
        }
        catch
        {
          // This may lead to problems with Silverlight
        }

The "rs" variable is always NULL, although the resource files exist.

Do you have any suggestions?? 

Thanks in advance
Bernardo

**Comment by MrCircuit** [comment]
I've no experience with caliburn micro - only some smaller localized plug-in projects with MEF. Could you please provide a sample project that demonstrates your setup and the problem. I will then try to find out what's going on...

**Comment by arcuri** [comment]
Sorry for the delay.. This is my simple application:
https://github.com/arcuri/SimpleGiotto

**Comment by SeriousM** [comment]
That's just a quick shot, but what if you're using "{lex:Loc
Shell:Italian}" instead of "{lex:Loc Italian}"?

**Comment by arcuri** [comment]
The problem is not in "SimpleGiotto.dll" but the localization doesn't work in "ExplorerApp.dll". Do you have other suggestions?

**Comment by SeriousM** [comment]
Same for the ExplorerApp: try use "{lex:Loc Explorer:Label}" instead of "{lex:Loc Label}"

**Comment by arcuri** [comment]
Still doesn't work

**Comment by UeliHilfiker** [comment]
Try to set the culture in ExplorerApp too, like:
`LocalizeDictionary.Instance.Culture = new CultureInfo("it");`
because ExplorerApp is in a separate project and it was not notified if the language was changed... (?)

**Comment by arcuri** [comment]
I have tried to notify the changes with a EventAggregator, but it doesn't s solve the problem.

**Comment by SeriousM** [comment]
Alright, I found the problem:

Your output the application to `bin/Debug` and the resource from ExplorerApp is located at `bin/Debug/Apps/it`. The reason why the `ExplorerApp.resources.dll` is not loaded is, that resources are searched in `bin/Debug/it` (without Apps).
Once you move the resources from your apps in the output folder's resource folders, everything works.

The solution to that:
A) you put your apps into the normal output folder
B) you search for the assemblies yourself on resolve-call (http://stackoverflow.com/a/23238712/660428)
C) I will add a function to the library so that you can add folders to check for (based on B)

**Comment by SeriousM** [comment]
@MrCircuit do we have a clean way to interact with the RESX provider over the extension?

**Comment by arcuri** [comment]
@SeriousM Great!!! Solution "B" fully works as expected! 
Many many thanks for the suggestion.

**Comment by SeriousM** [comment]
you're welcome!
