### ISSUE TITLE
Multiple format segments (FormatSegment1,2 etc.) not working when using ResxLocalizationProvider

### ISSUE THREAD

**Issue by DarkCloud14** [SeriousM/WPFLocalizationExtension#79]
Hello,

I've tried to use FormatSegment1, FormatSegment2 and FormatSegment3 but last two do not work properly during runtime!
During Designtime it shows the translations correctly but during runtime FormatSegment2 and FormatSegment3 are empty.

This is the xaml code of my TestWindow:

<pre><code>&lt;Window x:Class=&quot;MemoryTest.TestWindowAdditionalDictionary&quot;
        xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        xmlns:lex=&quot;http://wpflocalizeextension.codeplex.com&quot;
        lex:ResxLocalizationProvider.DefaultAssembly=&quot;MemoryTest&quot;
        lex:ResxLocalizationProvider.DefaultDictionary=&quot;Resources&quot;
        SizeToContent=&quot;WidthAndHeight&quot;
        Title=&quot;TestWindowAdditionalDictionary&quot;&gt;
  &lt;Grid&gt;
    &lt;Label Content=&quot;{lex:LocText FormatText, FormatSegment1={lex:LocText Test0815}, FormatSegment2={lex:LocText TestText}, FormatSegment3={lex:LocText TestText2}, Suffix=' [mm]'}&quot; FontStyle=&quot;Italic&quot; /&gt;
  &lt;/Grid&gt;
&lt;/Window&gt;</code></pre>

Does anybody have an idea how to fix that or what I'm doing wrong?
I'm using v2.3 but I've also tested it with latest sourcecode of WPFLocalizationExtension and the problem still exists there.

**Comment by SeriousM** [comment]
Hi, currently I have no idea why it's broken, but maybe #78 can help you out since @jongleur1983 is rebuilding it.

**Comment by DarkCloud14** [comment]
Hi,

looks like the problem only occurs if you try to use translatable text in FormatSegment1 and also in FormatSegment2, FormatSegment3 etc. the additional translation is only done for FormatSegment1 or better the first one that uses translatable text.

I've debugged a bit and maybe the problem is in XAMLMarkupExtensions not WPFLocalizationExtension.
What I found out so far is that the first time WPFLocalizationExtension tries to localize the texts of FormatSegment1, FormatSegment2 etc. the function FormatOutput is called for each but the endpoint parameter is null and so the function returns.

After that the FormatOutput gets called again with the endpoint parameter not null but in this case it's done just for FormatSegment1 and all others are skipped.

If you look at the code of NestedMarkupExtension class (XAMLMarkupExtensions) you see the following for event handler OnEndpointReached:

<pre><code>private void OnEndpointReached(NestedMarkupExtension sender, EndpointReachedEventArgs args)
{
    if (args.Handled)
        return;

    var path = GetPathToEndpoint(args.Endpoint);

    if (path == null)
        return;

    if ((this != sender) &amp;&amp; !UpdateOnEndpoint(path.EndPoint))
        return;

    args.EndpointValue = UpdateNewValue(path);
    args.Handled = true;
}</code></pre>

after <code>args.Handled</code> will be set to true after the first translatable FormatSegment and so the calls to update the endpoint for the following FormatSegments will be skipped as <code>args.Handled</code> is true..

If you move args.Handled outside the for loop which calls "OnEndPointReached" all FormatSegments will be translated as expected but I don't know which other impact that might have..

**Comment by jongleur1983** [comment]
I didn't see lex:LocText with the FormatSegment arguments before, but it looks helpful for #78 as well.
For this issue I'm testing currently, let's see....

**Comment by jongleur1983** [comment]
tested it now, the following works for me:

        <TextBlock Text="{lex:LocText simpleText}" />
        <TextBlock Text="{lex:LocText stringWithStringParam, FormatSegment1=Peter}" />
        <TextBlock Text="{lex:LocText stringWithStringParam, FormatSegment1={lex:LocText simpleText}}" />
        <TextBlock Text="{lex:LocText twoStringParams, FormatSegment1=Peter, FormatSegment2={lex:LocText thirty2}}" />
        <TextBlock Text="{lex:LocText twoStringParams, FormatSegment1={lex:LocText localizedName}, FormatSegment2={lex:LocText thirty2}}" />
1) a string without parameters,
2) one parameter that is not localized
3) one parameter that is localized
4) two parameters where the second is localized
5) two parameters where both are localized
6) two parameters where only the first is localized

**Comment by DarkCloud14** [comment]
Same here, as soon as you've multiple segments to translate only the first one gets translated at the moment.
As I said before maybe it's because of the endpoint handling in XAMLMarkupExtensions dll but I'm not sure if there is another way to get this working again.

**Comment by SeriousM** [comment]
Since @MrCircuit is the maintainer of XAMLMarkupExtension I need his advice in that.

**Comment by DarkCloud14** [comment]
That's fine, I mean it's just guess that this case is not handled correctly in XAMLMarkupExtension.
I'm not an expert and can just guess what the purpose of this handling is..

Maybe it's necessary to find another solution for WPFLocalizationExtension or in both projects to fix this.

**Comment by MrCircuit** [comment]
Hi there.
I'll have a look on that topic. Thanks for digging into it.

**Comment by DarkCloud14** [comment]
Hmm I'm not sure if it would be better then to override UpdateOnEndpoint in LocText and change the handling there. I mean I don't know what performance impact the change could have on other projects that may use XAMLMarkupExtension.

On the other side it may not be such a big impact as the foreach loop runs for every item in the list and doesn't break as soon as <code>args.Handled</code> is true.. Of course there might be slight impact as a few more checks will be done before OnEndpointReached returns..

During debugging the FormatSegment items where at the end of the list of the foreach loop and in such a case it wouldn't have a big performance impact I guess, if the items would be at the beginning of that list it might be a bit different but how much depends on what the invoked functions will do..

**Comment by DarkCloud14** [comment]
Looks like nobody else has an objection so why not.
Thanks!

**Comment by SeriousM** [comment]
> OK, then I'll change this in XamlMarkupExtensions.

Please link your changesets here for reference. Thank you :+1:

**Comment by MrCircuit** [comment]
hey cool, that worked :-)

**Comment by jongleur1983** [comment]
if that works, this issue could be closed, right? (I can't do that)

**Comment by DarkCloud14** [comment]
I think we can close this as soon as the XAMLMarkupExtensions dll are updated as for now it is just fixed in that project. @MrCircuit do you normally update those dlls or should I do that?

**Comment by MrCircuit** [comment]
The new DLLs are already available at Nuget.

**Comment by DarkCloud14** [comment]
Oh ok didn't see that, thought that the dlls in packages directory of WPFLocalizationExtension project here on GitHub will also be updated.

But anyway thanks for fixing it!

**Comment by MrCircuit** [comment]
OK, understood. I just updated the XAMLMarkupExtensions nuget package. But you can update this one via nuget without the need of updating the loc extension package.
