### ISSUE TITLE
GridViewColumn not localized

### ISSUE THREAD

**Issue by arcuri** [SeriousM/WPFLocalizationExtension#82]
Hi,
I have a problem with a localization. When I change the language, the Headers of GridViewColumns aren't localized. Infact appears "key:MyKeyword" etc. 

```
<GridViewColumnCollection x:Key="RuntimeColumns">
   <GridViewColumn Header="{lex:LocText HighTheshold}" Width="75"/>
   <GridViewColumn Header="{lex:LocText LowTheshold}" Width="75"/>
   <GridViewColumn Header="{lex:LocText Time}" Width="75"/>
</GridViewColumnCollection>
```

Do you have any suggestions?

**Comment by UeliHilfiker** [comment]
Did you try with extented or full notation, like:
`<GridViewColumn Header="{lex:LocText RessourceName:HighTheshold}" Width="75"/>`
or full notation
`<GridViewColumn Header="{lex:LocText AssemblyName:RessourceName:HighTheshold}" Width="75"/>`

**Comment by arcuri** [comment]
Thank you!
