### ISSUE TITLE
Translations for bindings

### ISSUE THREAD

**Issue by ZlobnyiSerg** [SeriousM/WPFLocalizationExtension#83]
Sorry guys I'm asking here. I need to translate bound value, for example:
```xml
<ItemsControl.ItemTemplate>
    <DataTemplate>
        <Label Content="{lex:BLoc Name}" />
    </DataTemplate>
</ItemsControl.ItemTemplate>
```
But this won't working - all values are empty (when other translathions with Loc extension are ok). How does it supposed to do with your library?

**Comment by SeriousM** [comment]
Due the nature of datatemplate it's impossible to determine the correct
assembly and dictionary.
Please use the full notation like {lex:BLoc Assembly:Dictionary:Name}
