### ISSUE TITLE
v2.3.2 NuGet package install on Silverlight error

### ISSUE THREAD

**Issue by papuashu** [SeriousM/WPFLocalizationExtension#84]
I tried to upgrade to v 2.3.2 an older solution with several Silverlight projects and got error:

Could not install package 'WpfLocalizeExtension 2.3.2'. You are trying to install this package into a project that targets 'Silverlight,Version=v5.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

So either remove from the package any Silverlight support, or include dlls for Silverlight.

**Comment by MrCircuit** [comment]
I found out, that in this particular package, the sl50 subtree is not located in the lib tree. This was not intended - the package must have been changed to this behaviour during upload. When I recreate the package using the nuspec template, everything is OK.

Strange.

I will double-check this issue at the next pending update.

**Comment by MrCircuit** [comment]
I've got a problem now: SL projects are not loadable any more at my dev PC (some updated must have removed a critical part). How should we proceed?

@SeriousM I think I know your opinion :-)...
