### ISSUE TITLE
Error: After a 'SetterBase' is in use (sealed), it cannot be modified.

### ISSUE THREAD

**Issue by vovakh** [SeriousM/WPFLocalizationExtension#85]
When I set Culture in runtime I get exception:
"After a 'SetterBase' is in use (sealed), it cannot be modified."

There is no such error if I set Culture in Application_Startup.

**Comment by MrCircuit** [comment]
You presumably used the loc extension in a Style Setter. This usage is limited due to the IsSealed property that is set after the Setter was created by the UI (by design of the WPF framework).

**Comment by SchwabenProgger** [comment]
So far I like this project well. Just the documentation and samples are very short.
For anyone who ends up having the same error:

If you want to localize within a style/trigger, do **NOT** use:
`<Setter Property="Content" Value="{lex:Loc YourKey}"/>`

but **instead**:
`<Setter Property="Content" Value="{lex:BLoc YourKey}"/>`

**Comment by VitorCastanheiro** [comment]
Hi,

I'm having the same issue and I've tried with BLoc too, but no text appears. I don't get an error, but...
the text is left blank! could you give me some guidance here?

thank you :)

**Comment by samarjit-r** [comment]
What's the difference between BLoc and Loc

**Comment by nzain** [comment]
> You presumably used the loc extension in a Style Setter. This usage is limited due to the IsSealed property that is set after the Setter was created by the UI (by design of the WPF framework).

@MrCircuit can you explain how to work around this? We use the WPFLocalizeExtension (together with this project) for several years and this exception happend for the first time now and, even worse, only on one particular machine. I can't reproduce it in the debugger even when using the exact same UI click sequence.

**Comment by dust63** [comment]
I had this issue.
For me I fix the issue by remove the fallbackvalue bind to the lex:Loc.

**Comment by dust63** [comment]
I had this issue too.
For me I fix the issue by remove the FallbackValue bind to the lex:Loc.

Original
```C#
<TextBlock Text="{Binding Header, FallbackValue={lex:Loc AssetDetails}}"/>
```
Fix
```C#
<TextBlock Text="{Binding Header="/>
```

**Comment by dust63** [comment]
I had this issue too.
For me I fix the issue by remove the FallbackValue bind to the lex:Loc.

Original

<TextBlock Text="{Binding Header, FallbackValue={lex:Loc AssetDetails}}"/>

Fix

<TextBlock Text="{Binding Header="}/>

**Comment by dust63** [comment]
I had this issue too.
For me I fix the issue by remove the FallbackValue bind to the lex:Loc.

Original
````C#
<TextBlock Text="{Binding Header, FallbackValue={lex:Loc AssetDetails}}"/>
````
Fix
````C#
<TextBlock Text="{Binding Header="}/>
````
