### ISSUE TITLE
Wrong unsubscribe from event

### ISSUE THREAD

**Issue by bisato** [SeriousM/WPFLocalizationExtension#86]
Hello,

can it be, that the Setter in Property "DefaultProvider" in https://github.com/SeriousM/WPFLocalizationExtension/blob/f8fce632fe897a17109dffd7de57479aa347dd3b/WPFLocalizeExtension/Engine/LocalizeDictionary.cs does a wrong unsubscribe?

Line 794: defaultProvider.ValueChanged += new ValueChangedEventHandler(ValueChanged);
should be: defaultProvider.ValueChanged -= new ValueChangedEventHandler(ValueChanged);

Thanks

Tobias

**Comment by SeriousM** [comment]
Hi Tobias, you're absolutely right! Thank you!
