### ISSUE TITLE
Publish new version with XAMLMarkupExtensions v1.2.1.4

### ISSUE THREAD

**Issue by SeriousM** [SeriousM/WPFLocalizationExtension#89]
Reference: https://github.com/MrCircuit/XAMLMarkupExtensions/issues/8

**Comment by SeriousM** [comment]
@MrCircuit, please publish it. I still can't build the package because of the damn WP7 project :angry:. Thank you!

**Comment by antibarbie** [comment]
BTW could you, like XAMLMarkupExtensions, publish the nuget for both .net3.5 and .NET4.0 ?

**Comment by MrCircuit** [comment]
Yes - it'll be published soon.
