### ISSUE TITLE
Gaps Release and DefaultValue in XAML

### ISSUE THREAD

**Issue by SecretOssi** [SeriousM/WPFLocalizationExtension#92]
Hello,

I just found this nice Project and use it for my current work.
I already found out about the Gaps (#78), but as i understood it they're not ready by now? I compiled the Version here from git but it always returns back to the demo assembly and strings ressource (seen while debugging). This will take a few time till release?

Another thing which would be great is the possibility to set a defualt value in XAML in case the Key doesn't exist. By now it says
Key: keyname
when the value doesn't exist. As is hortly researched it seems to be set in _LocExtension_ --> _FormatOutput_. I would add a DefaultValue Property and check if it has a value to set before setting last option Key: keyname.
Maybe a little thing that could be added (sorry, just new here and didn't checked how to do things myself)?

€: And a question: is there a way to get all Cultures i have with *.resx Files? Like
- TextObject.resx --> Invariant
- TextObjects.de.resx --> de
- TextObjects.fr.resx --> fr

I found a few Solutions, like Accessing _LocalizeDictionary.Instance.MergedAvailableCultures_ But id doesnt Gave me the expected Results.

**Comment by jongleur1983** [comment]
Hi,
the GapTextControl you referred to by issue #78 was my idea and I started the implementation.
There is something that could be approved there; e.g. more tests. I didn't try extensive styling, templating and so on yet and much more.

But in general the control should work, and I don't understand what you expected by just compiling it. The demo assembly isn't touched yet, that's true, but the fact that there's no demo doesn't mean the control isn't functional.

I don't promise anything about the time schedule for improvements, demos, documentation and tests as it's one of far too many side projects of mine, but I promise: If you or anyone else wants to contribute I personally am happy to help or accept changes (although I cannot talk about the WPFLocalization project itself, only about the GapTextControl branch as I am not a maintainer myself).

Regarding the other questions: You should split your question into different issues. By that it's easier to search for a question, easier to follow the discussion and easier to spot if one can help reading a single-topic issue. Just in short nevertheless: I don't think a default in XAML is a good idea. My personal tip: don't use string literals, but something like {lex:Loc {x:Static myStaticClass.Key}} where Key is a string constant in a static class. When you use the Strings.Designer.cs or another class generated with the localization file as a source you get compile time safety regarding undefined keys (of course not regarding undefined values in single languages).

**Comment by MrCircuit** [comment]
Hi,

Thank you @jongleur1983  for the comprehensive answer.

By now the Gap control is still under developement and needs to be tested.

Regarding the Key: keyname issue: We only have an attached property named: LocalizeDictionary.OutputMissingKeys (default: true). This can mute the output of these errors.

Regarding the Culture/resx issue: this behaviour was not intended. If you need it temporarily for development than I would suggest to derive the ResxLocalizationProvider class and hook into the moment where the LocalizeDictionary.Instance.MergedAvailableCultures list gets populated.
