### ISSUE TITLE
DefaultAssembly/Dictionary magic strings

### ISSUE THREAD

**Issue by zapacila89** [SeriousM/WPFLocalizationExtension#93]
Hello All,

I was thinking of a small improvement in terms of using magic strings when specifying the DefaultAssembly and DefaultDictionary. 
Why not define another dependency property of type "Type" and pass {x:Type MyAssembly.Resource.Language}. The Language type is the class generated by Visual Studio.

This would be an improvement for the following:
1. No magic strings
2. Faster ResourceManager lookup (although reflection would still be necessary to get the actual ResourceManager from the generated class)

Of course this is optional for the case when you have direct reference to the project/assembly containing the resx file. 

Looking forward for your feedback.

Kind regards,
Narcis

**Comment by MrCircuit** [comment]
I think I can imagine the point of your approach, but still have some issues in mind (especially Design-Time support). Could you create an example of your proposal?

**Comment by SeriousM** [comment]
Closed due stall conversation
