### ISSUE TITLE
Missing packages.config files for all projects in WPFLocalizeExtension - Demo.sln

### ISSUE THREAD

**Issue by xperiandri** [SeriousM/WPFLocalizationExtension#94]
In all the projects of `WPFLocalizeExtension - Demo.sln` solution `packages.config` files are missing

**Comment by MrCircuit** [comment]
I'm sorry, but the projects in this solution are very old and most of them fail to load in my current VS2015 :-(. Maybe we should think about removing them or should we keep it as a reference to our YouTube video @SeriousM ?
