### ISSUE TITLE
Localized KeyGesture

### ISSUE THREAD

**Issue by nzain** [SeriousM/WPFLocalizationExtension#95]
I'm looking into ways to localize a tooltip **and** KeyGesture (think of a button with keyboard shortcut), with the desired result

- [en] `This button does something (ctrl + H)`
- [de] `Macht irgendwas (strg + H)`

Note that the modifiers are localized, too. I know this is related to the every-once-and-then-raised question for localized texts with bindings (now gap text may offer a solution), but this is not exactly the same problem. `System.Windows.Input.KeyGesture` has a function `GetDisplayStringForCulture(CultureInfo c)` which returns the nicely formatted `"ctrl + H"` thing. Tricky part is how to integrate this with WPF-LocEx.

Different (unsatisfying) solutions:

1. I could hardcode key + modifier into the localization resources.
 - Drawback: The key/modifier must not change. Wenn key or modifier change, all localizations have to be updated and we have some customers that translate stuff themselves.
2. I could localize the tooltip message with WPF-LocEx and localize the gesture with the builtin function.
 - Drawback a) the latter is not sensitive to culture changes. I think one could work around this with weak references and a callback, though.
 - Drawback b) Cumbersome to use. The code here is terrible for such a small functionality.

            <Button Content="{lex:LocText MyButton}">
                <Button.ToolTip>
                    <TextBlock>
                        <Run Text="{lex:LocText MyButtonTooltip}"/>
                        <Run Text="("/><Run Text="{Binding KeyGestureText, Mode=OneWay}"/><Run Text=")"/>
                    </TextBlock>
                </Button.ToolTip>
            </Button>
 - Drawback c) The position of the gesture hint is hard coded.

I could not make this work with `StringFormat` of a Binding

    <TextBlock Text="{Binding KeyGestureText, StringFormat={lex:LocText KeyToFormattedTooltip}}"/>

Although the formatted tooltip is retreived (checked via debugger), it has no effect (not sure why, but I guess it is a known issue).

I was thinking of a similar solution to EnumRun, but could not make it work. Any directions?

**Comment by nzain** [comment]
Ok, it seems the function `KeyGesture.GetDisplayStringForCulture` does not, what I expected. On my system it always returns `"ctrl"` regardless of the culture argument. Kind of useless (?). I iterated over all available cultures using `CultureInfo.GetCultures()`... result is invariant.

Anyways, I've put together a UserControl (single TextBlock only) that takes a (localization dictionary) key and a `KeyGesture`. Much like the `EnumRun` it updates its text on every property change, but additionally registers in a custom `WeakReference` manager class that notifies all interested (alive) references about culture changes. So... theoretically, the gesture text would update dynamically too - practically, the above mentioned function does not work. Thus, I'm not sure if this has any relevance for other users. Furthermore, it is still cumbersome to use, mhh.

            <Button Command="{Binding ToggleUnitCommand}"
                    Content="{lex:LocText MainWindow/ChangeUnit}">
                <Button.ToolTip>
                    <ctrl:GestureTooltip Key="MainWindow/ChangeUnitTooltip"
                                         Gesture="{Binding ToggleUnitCommand.KeyGesture}" />
                </Button.ToolTip>
            </Button>

For your interest:
https://msdn.microsoft.com/en-us/library/system.windows.input.keygesture.getdisplaystringforculture(v=vs.110).aspx
https://stackoverflow.com/questions/35341543/show-inputgesturetext-as-a-tooltip-for-a-button


**Close unless you're interested.**

**Comment by MrCircuit** [comment]
Thanks for the investigations - I did not believe it but I also got the same string for all cultures for KeyGesture.GetDisplayStringForCulture. This is really weird.

In general - if the function would have worked - one could think of a callback functionality (e.g. an assignable Func<string, CultureInfo>), that could be overwritten by particular implementations, e.g. by deriving from the LocExtension. This would leave space for different tasks. Please open a feature request, if this is what you could need in future. Otherwise, I would recommend using the multiple-Run approach you proposed or the Cloze.
