### ISSUE TITLE
Huge Memory Leak by ToolTips Object : With Fix Proposal

### ISSUE THREAD

**Issue by XCasual** [SeriousM/WPFLocalizationExtension#97]
We have localized a huge memory leak in WPFLocalizeExtension.Provider by ParentChangedNotifiedHelper class.

The Function GetValueOrRegisterParentNotifier should be extended with 

if (depObj is System.Windows.Controls.ToolTip)
	break;

At Line 63-66, after this it works fine. At this moment we have like 5 Mb memory leak each time we switch the page. So it would be great if it would be fixed very soon.

**Comment by SeriousM** [comment]
Thank you for submitting the bug. I just created the fix, but @MrCircuit has to review it because I don't use WPF anymore.
Would you be kind and provide a working example where the memory leak can be observed / tested against after the fix is applied?

**Comment by XCasual** [comment]
![tooltip-memoryleak](https://cloud.githubusercontent.com/assets/11887533/14564484/010c6436-0327-11e6-80bb-2259b8f69b87.png)
I can make a test after but I can't attach the App. We have a Delta von unter +10MB with the fix and more than +40MB after 130 interaction with current script. The Tooltips are saved as an Referenz in ResxLocalizationProvider and ParentChangedNotifier.OnParentChangedList hold them in Memory. If we skip them there are not there anymore and still will be translated.

**Comment by SeriousM** [comment]
Yes, I guess WPF does not cache the tooltips but create a new one every time, is that true?
at least it would explain the behavior.

we need to wait for @MrCircuit for the deployment :(

**Comment by MrCircuit** [comment]
Sorry - I was under heavy load the last weeks. I scheduled myself to work on this topic at latest this weekend. If not done, please remind me.
